const trackNames={ios:'iOS / Swift / SwiftUI',android:'Android / Kotlin / Compose',rn:'React Native internals',architecture:'Mobile architecture & security',cloud:'Cloud / AWS',ai:'AI engineering',staff:'Staff leadership',dsa:'DSA & interview practice'};
const learningDefaults=()=>({ratings:{},attempts:[]});
const previousBase=baseState;baseState=()=>({...previousBase(),learning:learningDefaults()});
const previousNormalize=normalize;normalize=data=>{const result=previousNormalize(data),l=result.learning||learningDefaults();if(!l||typeof l!=='object'||!l.ratings||typeof l.ratings!=='object'||Array.isArray(l.ratings)||!Array.isArray(l.attempts))throw Error('Invalid learning backup');if(Object.values(l.ratings).some(v=>![0,1,2].includes(v)))throw Error('Invalid learning rating');if(l.attempts.some(a=>!a||typeof a.id!=='string'||typeof a.date!=='string'||typeof a.track!=='string'||!Array.isArray(a.answers)||a.answers.some(r=>!r||typeof r.id!=='string'||typeof r.response!=='string'||![0,1,2].includes(r.score))))throw Error('Invalid assessment history');result.learning=l;return result};
state=normalize(state);
const learning=document.createElement('section');learning.className='section';learning.id='learning';learning.innerHTML=`<div class="section-head"><div><p class="eyebrow">KNOWLEDGE / RECALL / REPEAT</p><h2>Your interview refresh library.</h2></div><p class="section-note">${learningBank.length} original Q&As · 8 tracks · retake anytime</p></div><p class="muted">A focused foundation for your Staff Mobile → Architect path, not an exhaustive syllabus or certification exam dump. Source links are further reading. Validate API details against your project's SDK versions.</p><div class="learning-controls"><label>Track<select id="learningTrack"><option value="all">All tracks</option>${Object.entries(trackNames).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>Search Q&A<input id="learningSearch" type="search" placeholder="Actors, offline sync, Fabric…"></label><label>Library filter<select id="learningFilter"><option value="all">All questions</option><option value="weak">Needs refresh</option><option value="unseen">Not assessed yet</option><option value="strong">Strong recall</option></select></label></div><div class="card v2panel assessment-setup"><div><h3>Assess your recall</h3><p class="muted">Explain an answer before revealing it. Compare with the rubric and self-score: 0 = needs work, 1 = partial, 2 = strong. Scores reflect your self-assessment, not automatic or AI grading. Search applies to the library; assessments use the selected track and scope.</p></div><label>Scope<select id="assessmentScope"><option value="all">Everything in selected track</option><option value="ten">10 shuffled questions</option><option value="weak">Previously missed / partial</option></select></label><button class="primary" id="startAssessment">Start / retake</button></div><p class="muted" role="status" id="learningMessage"></p><div id="assessmentPanel" class="card v2panel hidden" tabindex="-1"></div><div id="learningStats" class="learning-stats"></div><div id="learningList" class="learning-list"></div><article class="card v2panel history-panel"><h3>Assessment history</h3><p class="muted">Completed attempts and written answers are included in your Export backup.</p><div id="learningHistory"></div></article>`;
document.querySelector('#interview').before(learning);
document.querySelector('.hero-actions').insertAdjacentHTML('beforeend','<a class="secondary" href="#learning">Q&A + assessments →</a>');
document.querySelector('.topnav').insertAdjacentHTML('beforeend','<a href="#learning">Learn</a>');
let activeAssessment=null,lastAssessmentIds=[];
function shuffled(list){const result=[...list];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
function selectedQuestions(){const track=document.querySelector('#learningTrack').value;return learningBank.filter(q=>track==='all'||q.track===track)}
function assessmentQuestions(){const scope=document.querySelector('#assessmentScope').value;let questions=selectedQuestions();if(scope==='weak')questions=questions.filter(q=>state.learning.ratings[q.id]!==undefined&&state.learning.ratings[q.id]<2);questions=shuffled(questions);return scope==='ten'?questions.slice(0,10):questions}
function ratingLabel(q){const score=state.learning.ratings[q.id];return score===undefined?'Not assessed':score===2?'Strong recall':score===1?'Partial recall':'Needs refresh'}
function renderLearning(){
 const selected=selectedQuestions(),text=document.querySelector('#learningSearch').value.trim().toLowerCase(),filter=document.querySelector('#learningFilter').value;
 const list=selected.filter(q=>`${q.topic} ${q.q} ${q.a} ${trackNames[q.track]}`.toLowerCase().includes(text)).filter(q=>{const r=state.learning.ratings[q.id];return filter==='all'||filter==='weak'&&r!==undefined&&r<2||filter==='unseen'&&r===undefined||filter==='strong'&&r===2});
 document.querySelector('#learningStats').textContent=`${list.length} shown / ${selected.length} in track · ${selected.filter(q=>state.learning.ratings[q.id]===2).length} strong · ${selected.filter(q=>state.learning.ratings[q.id]!==undefined&&state.learning.ratings[q.id]<2).length} to refresh`;
 document.querySelector('#learningList').innerHTML=list.map(q=>`<details class="card qa-card"><summary><span class="label">${esc(trackNames[q.track])} / ${esc(q.topic)}</span><strong>${esc(q.q)}</strong><small>${ratingLabel(q)}</small></summary><div class="qa-answer"><p>${esc(q.a)}</p><p class="label">CHECK YOUR ANSWER</p><ul>${q.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul><a class="table-link" href="${q.source[1]}" target="_blank" rel="noreferrer">${esc(q.source[0])} ↗</a><button class="secondary small" data-practice="${q.id}">Practice this question</button></div></details>`).join('')||'<p class="empty">No matching questions. Change the search or filter.</p>';
 document.querySelectorAll('[data-practice]').forEach(b=>b.onclick=()=>startAssessment([learningBank.find(q=>q.id===b.dataset.practice)]));
 document.querySelector('#learningHistory').innerHTML=[...state.learning.attempts].reverse().map(a=>{const sum=a.answers.reduce((n,r)=>n+r.score,0),max=a.answers.length*2;return `<details class="attempt"><summary>${esc(a.date)} · ${esc(a.track)} · ${max?Math.round(sum/max*100):0}% self-score · ${a.answers.length} questions</summary>${a.answers.map(r=>{const q=learningBank.find(q=>q.id===r.id);return `<div class="history-answer"><strong>${esc(q?.q||r.id)} · ${r.score}/2</strong><p>${esc(r.response||'(No written answer)')}</p></div>`}).join('')}</details>`}).join('')||'<p class="muted">No completed assessments yet.</p>';
}
function startAssessment(questions){if(!questions.length){document.querySelector('#learningMessage').textContent='No questions available for that scope. Try all questions or another track.';return}if(activeAssessment&&!confirm('Discard the current unfinished assessment and start again?'))return;lastAssessmentIds=questions.map(q=>q.id);activeAssessment={questions,index:0,answers:[],draft:'',revealed:false};document.querySelector('#learningMessage').textContent='';renderAssessment();document.querySelector('#assessmentPanel').scrollIntoView({behavior:'smooth',block:'start'});document.querySelector('#assessmentPanel').focus()}
function renderAssessment(){
 const panel=document.querySelector('#assessmentPanel');panel.classList.remove('hidden');const run=activeAssessment,q=run.questions[run.index];
 panel.innerHTML=`<div class="card-title"><p class="label">QUESTION ${run.index+1} / ${run.questions.length} · ${esc(trackNames[q.track])}</p><button class="ghost small" id="cancelAssessment">End without saving</button></div><h3>${esc(q.q)}</h3><label class="recall-label" for="recallResponse">Your answer (optional: say it aloud)</label><textarea id="recallResponse" rows="5" maxlength="6000" placeholder="Explain the concept, tradeoffs, failure cases, and how you would verify it.">${esc(run.draft)}</textarea>${run.revealed?`<div class="revealed-answer"><p class="label">MODEL ANSWER / SUGGESTED RUBRIC</p><p>${esc(q.a)}</p><ul>${q.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul><a class="table-link" href="${q.source[1]}" target="_blank" rel="noreferrer">Further reading ↗</a><p>How closely did your answer cover the rubric?</p><div class="rating-actions"><button class="secondary" data-score="0">0 · Needs work</button><button class="secondary" data-score="1">1 · Partial</button><button class="primary" data-score="2">2 · Strong</button></div></div>`:'<button class="primary" id="revealAnswer">Reveal answer + rubric</button>'}`;
 document.querySelector('#recallResponse').oninput=e=>run.draft=e.target.value;
 document.querySelector('#cancelAssessment').onclick=()=>{if(confirm('End this attempt? Unfinished answers will not be saved.')){activeAssessment=null;panel.classList.add('hidden')}};
 if(!run.revealed)document.querySelector('#revealAnswer').onclick=()=>{run.revealed=true;renderAssessment()};
 panel.querySelectorAll('[data-score]').forEach(b=>b.onclick=()=>{run.answers.push({id:q.id,response:run.draft,score:Number(b.dataset.score)});run.index++;if(run.index<run.questions.length){run.draft='';run.revealed=false;renderAssessment();panel.focus()}else finishAssessment()});
}
function finishAssessment(){
 const run=activeAssessment,tracks=[...new Set(run.questions.map(q=>trackNames[q.track]))];const attempt={id:crypto.randomUUID(),date:new Date().toLocaleString('en-IN'),track:tracks.length===1?tracks[0]:'Mixed tracks',answers:run.answers};
 state.learning.attempts.push(attempt);for(const answer of run.answers)state.learning.ratings[answer.id]=answer.score;save();activeAssessment=null;const total=attempt.answers.reduce((n,r)=>n+r.score,0),weak=attempt.answers.filter(r=>r.score<2);
 document.querySelector('#assessmentPanel').innerHTML=`<p class="label">ASSESSMENT COMPLETE</p><h3>${Math.round(total/(attempt.answers.length*2)*100)}% self-assessed recall</h3><p>${attempt.answers.length} questions completed · ${weak.length} to refresh. Your last rating guides the Needs refresh filter; earlier attempts stay in history.</p><div class="rating-actions"><button class="primary" id="retakeSame">Retake these questions</button><button class="secondary" id="retakeMissed" ${weak.length?'':'disabled'}>Retake missed / partial</button><button class="ghost" id="closeResults">Close results</button></div>`;
 document.querySelector('#retakeSame').onclick=()=>startAssessment(shuffled(lastAssessmentIds.map(id=>learningBank.find(q=>q.id===id))));document.querySelector('#retakeMissed').onclick=()=>startAssessment(shuffled(weak.map(r=>learningBank.find(q=>q.id===r.id))));document.querySelector('#closeResults').onclick=()=>document.querySelector('#assessmentPanel').classList.add('hidden');renderLearning();
}
document.querySelector('#startAssessment').onclick=()=>startAssessment(assessmentQuestions());
for(const id of ['learningTrack','learningFilter'])document.querySelector(`#${id}`).onchange=renderLearning;
document.querySelector('#learningSearch').oninput=renderLearning;renderLearning();save();
