const learningSources={
 ios:['Swift language guide','https://docs.swift.org/swift-book/documentation/the-swift-programming-language/'],
 android:['Android architecture guidance','https://developer.android.com/topic/architecture'],
 rn:['React Native documentation','https://reactnative.dev/docs/getting-started'],
 architecture:['OWASP mobile security reference','https://mas.owasp.org/'],
 cloud:['AWS architecture framework','https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html'],
 ai:['Google machine learning guides','https://developers.google.com/machine-learning/resources'],
 staff:['Google engineering practices','https://google.github.io/eng-practices/'],
 dsa:['MIT algorithms course','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/']
};
// Original study summaries and suggested interview rubrics, not copied exam questions.
const learningRows=`
ios|Swift values vs references|When would you use a struct instead of a class?|Use a struct for value semantics and independent copies of a model; collections may optimize storage with copy-on-write. Use a class for shared identity, inheritance, or reference-based lifecycles. Value semantics alone do not make arbitrary shared mutation safe.|Value semantics;Shared identity;Concurrency caveat
ios|ARC and retain cycles|How do you diagnose and fix a closure retain cycle?|ARC releases an instance when strong references disappear. A stored closure capturing its owner strongly can form a cycle. Inspect the memory graph, decide ownership, and use weak capture when the owner may disappear. Unowned capture requires a guaranteed lifetime; it can crash otherwise.|Ownership graph;Weak vs unowned;Memory graph verification
ios|Structured concurrency|How do async let, task groups, and Task differ?|Async let and task groups create child work scoped to the parent and coordinate completion and cancellation. Task creates unstructured work; retain its handle if you need explicit cancellation. Await suspends a task rather than guaranteeing a new background thread. Choose task scope to match ownership.|Child lifetime;Cancellation;Await is suspension
ios|Actors and reentrancy|Can an actor have a logical race even without a data race?|An actor isolates mutable state, but other actor work may execute while a method is suspended at await. Recheck assumptions after suspension, capture version tokens, or keep a state transition within a synchronous isolated segment. An actor method is not an atomic transaction across every await.|Isolation;Reentrancy at await;Revalidate assumptions
ios|MainActor and Sendable|What do MainActor and Sendable actually guarantee?|MainActor isolates UI-related work to the main actor. Sendable describes values safe to transfer across concurrency domains. Neither says heavy computation belongs on the UI executor. Prefer immutable transferable models and explicit isolation; avoid unchecked conformance without proving synchronization.|UI isolation;Safe transfer;Avoid unchecked shortcuts
ios|SwiftUI state ownership|How do you choose State, Binding, StateObject, and ObservedObject?|State owns view-local state; Binding borrows mutable access. In the ObservableObject model, StateObject owns a reference model for a view identity and ObservedObject observes an externally owned one. With Observation, State can own an Observable model and Bindable creates bindings. Match deployment target and model style.|Owner vs borrower;View identity;Observation distinction
ios|SwiftUI identity and effects|Why can a SwiftUI list lose row state or repeat network work?|Row identity governs lifetime; unstable identifiers can recreate views and state. Keep stable domain IDs. Keep view construction free of side effects, use lifecycle-bound task work, and cancel or deduplicate requests when inputs change. Measure invalidations instead of adding random caching.|Stable IDs;Effect ownership;Cancellation or deduplication
ios|iOS performance and testing|How would you investigate a slow launch and memory growth?|Measure release builds on representative devices, separate cold from warm launch, and use Instruments to locate main-thread work, allocations, or leaks. Defer nonessential setup and reduce image memory. Add regression measurements plus unit tests for data flow and UI tests for critical journeys.|Measured baseline;Instruments;Regression evidence
android|Coroutines and dispatchers|Does a suspend function automatically run in the background?|No. Suspend means the function can suspend; it can still execute blocking work on its caller context. Make repository APIs main-safe by moving blocking I/O or CPU work to appropriate dispatchers. Inject dispatchers for deterministic tests and avoid blocking the main thread.|Suspension vs thread;Main-safe APIs;Injected dispatchers
android|Coroutine cancellation|Why does cancellation sometimes fail to stop expensive work?|Cancellation is cooperative. Suspending cancellable APIs check it, but a CPU loop must check cancellation or yield. Do not swallow CancellationException. Tie work to its lifecycle and use cleanup in finally; reserve non-cancellable cleanup for short required operations.|Cooperation;CancellationException;Lifecycle ownership
android|Flow and StateFlow|When do you use Flow, StateFlow, or SharedFlow?|A cold Flow starts production for each collector. StateFlow holds a current state and conflates equal updates. SharedFlow broadcasts emissions with configurable replay and buffering. Model durable UI state separately from effects and consider lifecycle gaps so critical outcomes are not silently lost.|Cold vs hot;Current state;Replay and lifecycle gaps
android|Compose state|How do remember and rememberSaveable differ?|Remember retains a value while its composition identity exists. RememberSaveable also supports saved-state restoration for compatible values or a saver. Keep saved UI state small, use ViewModel for screen logic, and use persistent storage for durable data. Ordinary mutable collections are not automatically observable.|Composition lifetime;Saved state limits;Durable storage
android|Compose effects|How do you avoid repeated side effects during recomposition?|Composables should describe UI. Use LaunchedEffect for composition-scoped suspending work keyed by its inputs and DisposableEffect for setup needing cleanup. RememberUpdatedState supplies a latest value without restarting an effect. Move business operations into lifecycle-owned logic when appropriate.|Effect keys;Cleanup;Business logic ownership
android|Room and offline-first|What should the UI observe in an offline-first Android app?|Expose local database data through the repository as the source read by higher layers. Network work refreshes local records. Persist pending mutations, handle retries and conflicts, and expose sync status. Room transactions protect local atomicity but do not make server operations globally atomic.|Local read source;Persistent outbox;Conflict handling
android|Hilt and module boundaries|How do you stop a large Android app becoming tightly coupled?|Separate features and stable domain or data interfaces, keep dependency direction explicit, and inject implementation dependencies. Scope Hilt bindings to required lifetimes rather than treating every dependency as a singleton. Check build times and dependency cycles; modularity has maintenance costs.|Dependency direction;Appropriate scopes;Build and complexity tradeoffs
android|Process death and performance|What survives configuration change, and how do you test startup?|A ViewModel can survive configuration changes but not process death. Restore minimal state with saved-state APIs and durable records from storage. Benchmark release-like startup and scrolling with Macrobenchmark, and evaluate Baseline Profiles. Validate on realistic devices and separately test process recreation.|ViewModel limits;Saved vs durable state;Release benchmarks
rn|JSI and the bridge|What changes when moving from the old bridge to JSI?|JSI provides a C++ interface between the JavaScript runtime and native code, avoiding dependence on the old serialized asynchronous bridge. It enables direct interop; it does not remove all conversion costs or make every API synchronous, thread-safe, or fast. Profile the specific call path.|C++ interop;No old bridge dependency;Costs still exist
rn|Fabric pipeline|Explain render, commit, and mount in Fabric.|Render produces a new shadow tree from React work. Commit prepares a complete tree including layout and promotes it for mounting. Mount applies the resulting changes to native host views. Distinguish JS, C++ renderer, and platform UI work when diagnosing a slow update.|Shadow tree;Commit and layout;Native mounting
rn|TurboModules and Codegen|What is the role of Codegen in a native module?|Define a typed JavaScript or TypeScript specification and let Codegen generate binding interfaces used by native implementations. TurboModules integrate with the new module system and can be loaded lazily. Generated interfaces help interoperability; you still own validation, errors, lifecycle, and API compatibility.|Typed specification;Generated bindings;Native responsibility
rn|Threading and sync calls|Is a synchronous native call always a performance improvement?|No. A synchronous call blocks its caller until completion; expensive work can stall JavaScript or UI execution. Understand the specific module and renderer threading contract, offload costly work appropriately, and return asynchronous results when useful. Never assume JSI supplies automatic thread safety.|Blocking caller;Explicit thread contract;Async expensive work
rn|Hermes and profiling|What does Hermes solve, and what does it not solve?|Hermes is a JavaScript engine optimized for React Native, including ahead-of-time bytecode workflows. Startup and memory benefits depend on the app and build. It does not eliminate excessive renders, slow native code, or huge assets. Profile release builds and isolate JS versus UI bottlenecks.|Engine role;App-specific measurement;JS vs UI bottlenecks
rn|List performance|How do you investigate jank in a large React Native list?|Check stable item keys, render frequency, expensive row work, image sizing, and virtualization settings. Memoize only after locating meaningful repeated work, provide layout information when valid, and tune windows for memory versus blank-area tradeoffs. Measure release performance rather than development behavior.|Stable rows;Virtualization tradeoffs;Measured optimization
rn|Native lifecycle|What makes a native Swift or Kotlin module production-ready?|Specify threading and ownership, validate inputs, map failures to a stable API, and release listeners and resources when the module invalidates. Avoid retaining an obsolete Activity or view controller. Test reloads, background transitions, permissions, and binary compatibility with the JS bundle.|Ownership and cleanup;Stable errors;Lifecycle and compatibility tests
rn|New Architecture migration|How would you migrate a production app safely?|Inventory native dependencies and compatibility, establish startup and crash baselines, and validate core journeys under the new architecture. Migrate incrementally where possible and use staged releases with measurable rollback criteria. OTA changes must remain compatible with the installed native binary.|Dependency audit;Baseline and critical tests;Staged rollout and OTA safety
architecture|Offline sync|Design an offline-first app with concurrent edits.|Read from durable local data, record changes in an outbox, and synchronize through idempotent server operations. Define conflict policy using versions or domain rules; timestamps alone may be unreliable. Show pending and failed changes, and reconcile after reconnect without losing the user's work.|Outbox;Idempotency and versions;Visible conflict policy
architecture|Authentication|How do you handle ten requests receiving an expired-token response?|Use a single-flight refresh operation so concurrent callers share one refresh. Retry requests with bounded policy, avoid loops, and handle revoked credentials by transitioning to sign-in. Store credentials securely, never log them, and keep server authorization as the actual access boundary.|Single-flight refresh;Bounded retries;Secure storage and server auth
architecture|API evolution|How do you support users running old mobile versions?|Use backward-compatible API changes, capability negotiation where needed, and server tolerance for missing optional fields. Measure adoption before removing contracts, define minimum supported versions, and plan staged migrations. A backend deployment must not assume all installed clients update immediately.|Installed client lag;Compatible contracts;Measured deprecation
architecture|Mobile security|What belongs in a mobile threat model?|Identify assets, trust boundaries, attacker capabilities, and abuse cases. Protect credentials with platform storage, verify transport, minimize data, and enforce authorization server-side. A mobile binary cannot safely conceal a long-lived privileged secret. Evaluate controls against realistic threats and privacy needs.|Threat model;No privileged client secret;Server enforcement
architecture|Performance budgets|How do you define a mobile performance strategy?|Set budgets for startup, frame time, memory, network bytes, and battery around real user journeys and representative devices. Instrument percentiles and regressions, then assign ownership. Optimize measured bottlenecks and compare controlled builds; average timings alone can hide a poor tail experience.|Journey budgets;Percentiles and representative devices;Regression ownership
architecture|Observability|How do you trace a failing checkout across client and backend?|Correlate privacy-safe request and session identifiers, structured events, client errors, and backend traces. Distinguish crash-free sessions from transaction success and latency. Include app version and rollout cohort, redact sensitive fields, and create alerts based on user impact.|Correlation;User outcomes;Redaction and release context
architecture|Feature flags and release|What makes a mobile rollout reversible?|Use staged distribution and feature flags with safe defaults and server-side control where applicable. Define rollback or kill-switch thresholds from crash, performance, and business metrics. Some binary changes cannot be undone instantly on installed devices, so preserve compatible server behavior.|Safe defaults;Measurable thresholds;Installed binary limitation
architecture|Platform architecture|Design a codebase used by fifty mobile engineers.|Create stable feature boundaries, platform services, dependency rules, test contracts, and clear owners. Track build and release friction as well as reliability. Use an RFC for cross-team decisions and evolve boundaries from actual coupling; excessive fragmentation can slow delivery just as a monolith can.|Boundaries and ownership;Platform contracts;Tradeoff metrics
cloud|AWS architecture|What are the AWS Well-Architected pillars for?|They guide review of operational excellence, security, reliability, performance efficiency, cost optimization, and sustainability. Use them to expose tradeoffs and improvement actions for a workload rather than treat a checklist as proof of correctness. Tie decisions to requirements and measured outcomes.|Six pillars;Tradeoffs;Actionable review
cloud|API gateway and authorization|What belongs at an API gateway versus in a service?|A gateway can manage routing, throttling, and token validation. The service must still enforce resource-level authorization and domain rules. Validate audience and issuer where applicable, propagate correlation metadata, and avoid relying on a client-supplied user ID as evidence of identity.|Gateway responsibilities;Resource authorization;Identity validation
cloud|Queues and idempotency|How do you handle duplicate event delivery?|Assume duplicates unless a system's exact contract says otherwise. Give operations stable idempotency keys, record processing outcomes atomically with relevant state, and retry safely. Use dead-letter handling and replay tooling. Ordering guarantees are scoped and do not automatically solve duplicates.|Stable keys;Atomic outcome;Replay and dead letters
cloud|Database selection|How do you choose SQL, NoSQL, and a cache?|Start with access patterns, consistency requirements, transactions, scale, and operations. SQL often fits relational constraints and transactions; NoSQL designs vary widely by product. Add a cache when evidence justifies it and specify invalidation. Avoid choosing a database solely because it is fashionable.|Access patterns;Consistency and transactions;Cache invalidation
cloud|Reliability|How would you make a mobile backend resilient?|Define service objectives, remove critical single points where required, and design bounded retries, timeouts, backpressure, and graceful degradation. Spread across failure domains as requirements justify. Test recovery and backups. Multi-region complexity is a tradeoff, not a default badge of reliability.|SLOs;Bounded failure handling;Recovery testing
cloud|Caching and CDN|What can go wrong when caching authenticated content?|A cache key missing identity or authorization context can expose one user's content to another. Set correct private or public cache controls, avoid caching secrets, and define freshness and invalidation. Use CDN delivery for suitable static assets and test behavior after permission changes.|Isolation in keys;Cache controls;Permission invalidation
cloud|AWS IAM|How do you give a mobile client access to cloud resources?|Use an appropriate identity flow and short-lived narrowly scoped credentials when direct access is justified, or route through an authorized backend. Do not embed long-lived IAM access keys. Apply least privilege, distinguish authentication from permissions, and audit access and credential rotation.|No long-lived keys;Least privilege;Short-lived identity flow
cloud|Certification readiness|How do you know you are ready for an architecture exam?|Map preparation to the current official exam guide, explain scenario tradeoffs, and practice timing with legitimate materials. Review mistakes by domain and reproduce relevant architecture decisions in a small lab. A practice percentage is feedback, not a guarantee of passing or a substitute for engineering evidence.|Current guide;Scenario tradeoffs;Mistake-driven practice
ai|LLM boundaries|What can an LLM-powered mobile feature promise?|An LLM generates probabilistic outputs and can be wrong even when confident. Define supported tasks, uncertainty and fallback behavior, and keep critical decisions in validated code or authorized workflows. Minimize sensitive input and evaluate quality on representative user scenarios before rollout.|Probabilistic errors;Supported scope;Validated critical decisions
ai|Structured outputs|Does valid JSON guarantee a correct AI answer?|No. Shape validation checks format, not truth or authorization. Use an explicit schema where supported, validate values and business constraints, and handle refusals or incomplete outputs. Treat generated identifiers and tool arguments as untrusted until checked against allowed operations and real data.|Format vs semantics;Validation;Failure handling
ai|RAG|How do you debug a RAG system giving wrong answers?|Separate ingestion, chunking, retrieval, ranking, and generation. Check whether the correct evidence was available and retrieved, then whether the answer is grounded in it. Evaluate citations and retrieval recall on held-out cases. More context can add noise and does not repair bad source data.|Pipeline diagnosis;Grounding;Held-out retrieval evaluation
ai|Tools and agents|How do you make tool execution safe?|Expose narrow typed tools, validate arguments, enforce user permissions on every call, and require review for consequential operations when appropriate. Limit steps and costs, log outcomes safely, and design retryable idempotent actions. Model instructions do not replace access control.|Narrow tools;Server permissions;Bounded idempotent actions
ai|Prompt injection|Why is retrieved text a security boundary?|Retrieved pages, files, and tool results can contain attacker-controlled instructions. Treat them as data, separate them from trusted policies, restrict tool permissions, and validate outputs before action. Prompt wording alone is not a reliable security control; test adversarial inputs and containment.|Untrusted content;Access control;Adversarial testing
ai|Evaluation|What would you measure before shipping an AI assistant?|Build a representative versioned evaluation set including failures and adversarial cases. Measure task success, factual grounding, unsafe actions, latency, and cost. Combine deterministic checks with human review where judgment matters, and monitor production drift without storing unnecessary sensitive data.|Representative evals;Quality plus cost and latency;Human review and drift
ai|Streaming and mobile UX|What can go wrong with streaming responses?|Users may see incomplete or invalid intermediate output. Define cancellation, retry, reconnection, and state restoration; separate provisional text from committed actions. Buffer structured data until validated. Instrument time to first useful output as well as completion time, and avoid duplicating actions after reconnect.|Partial output;Cancellation and reconnect;Validated actions
ai|On-device versus cloud AI|How do you choose where inference runs?|Compare model capability, latency, privacy, battery, memory, device coverage, and update size. On-device inference can reduce network dependence but may limit quality or strain resources. Cloud inference adds connectivity and data-handling concerns. Use a measured hybrid or fallback policy where useful.|Quality and resources;Privacy and network;Measured fallback
staff|Architecture decisions|What makes a good architecture decision record?|State the problem, constraints, options, chosen tradeoffs, and consequences. Include why alternatives were rejected, measurable success criteria, ownership, and a revisit trigger. Keep it short enough to use; an ADR captures context rather than asserting a design is universally best.|Alternatives;Consequences;Revisit criteria
staff|Disagreement|How do you resolve an architectural disagreement?|Clarify shared goals and constraints, represent competing proposals fairly, and agree on decision ownership. Gather targeted evidence through a bounded experiment when needed. Record the tradeoff, commit to the decision, and revisit if agreed metrics fail rather than debating preferences indefinitely.|Shared goals;Evidence;Decision and revisit ownership
staff|Mentoring|How do you demonstrate mentoring impact?|Explain the person's starting challenge, how you supported independent judgment, and what changed over time. Use concrete feedback and outcomes such as design ownership or reduced support needs. Give credit accurately; mentoring is developing autonomy rather than doing the work for someone.|Starting context;Autonomy;Observed outcome
staff|Incidents|What should a Staff engineer do during and after an incident?|Prioritize user impact and containment, establish clear roles and communications, and avoid speculative changes. After recovery, build a timeline, identify contributing system conditions, and assign prevention actions with owners. A blameless review still requires accountability for improvement.|Containment;Clear communication;Owned prevention actions
staff|Influence without authority|How do you get several teams to adopt a platform standard?|Learn each team's constraints, involve them in the design, and provide migration support and a clear benefit. Pilot with willing partners and measure friction and outcomes. Prefer credible evidence and useful defaults over mandates that move hidden costs onto product teams.|Stakeholder constraints;Migration support;Measured adoption
staff|Technical debt|How do you prioritize debt against feature work?|Describe a specific risk or recurring cost, quantify it where possible, and propose a bounded investment with expected benefit. Compare against product priorities and use incremental delivery. Track whether the change actually improves reliability, build time, or developer effort.|Concrete cost;Bounded plan;Outcome measurement
staff|STAR stories|What distinguishes a strong senior or Staff interview story?|Give concise situation and stakes, your actual responsibility, the decisions and tradeoffs you made, and evidence of results. Explain your contribution separately from team work and include lessons. Use sanitized facts and honest metrics; a long technology list does not demonstrate influence.|Personal contribution;Tradeoffs;Results and lessons
staff|Mobile Platform Lab|What should your showcase prove at eleven years of experience?|Demonstrate one coherent architecture with native interoperability, offline behavior, observability, and reliable delivery. Include ADRs, reproducible benchmarks, a diagram, a concise demo, and failure tests. Explain limitations honestly. Depth and decision evidence matter more than another broad feature checklist.|Coherent architecture;Reproducible evidence;Failures and limitations
dsa|Complexity|How do you explain an algorithm's complexity well?|Define input size, identify the dominant operations, and state worst-case time and auxiliary space. Separate output storage from working memory and distinguish expected bounds from worst-case bounds. Validate your reasoning against edge cases instead of inferring complexity from a single loop count.|Input definition;Time and space;Worst vs expected
dsa|Hash maps|When can a hash-map solution have hidden tradeoffs?|Hash maps often give expected constant-time operations, but collisions and implementation details affect worst cases. They use extra memory and may not preserve the order you need. Explain key equality, duplicates, and whether a deterministic sorted approach is preferable for constraints.|Expected bounds;Memory;Duplicates and ordering
dsa|Sliding window|When is a sliding-window algorithm valid?|Maintain an invariant over a contiguous region and update it as endpoints move. It works when the constraint permits predictable expansion and shrinking; negative numbers can break simple sum-based monotonic reasoning. State the invariant and prove why discarded positions cannot improve the result.|Contiguous invariant;Monotonic requirement;Correctness argument
dsa|Binary search|How do you avoid binary-search boundary bugs?|Define whether bounds are closed or half-open, specify the monotone predicate, and preserve the search invariant on every update. Use a safe midpoint calculation and ensure progress. Test empty, one-element, duplicates, and answers at both extremes; searching a boundary differs from searching exact equality.|Bounds;Monotone invariant;Progress and edge cases
dsa|BFS and DFS|When would you choose BFS rather than DFS?|BFS finds shortest paths by edge count in an unweighted graph by exploring layers. DFS suits traversal, cycle reasoning, and backtracking depending on the problem. Mark visited nodes appropriately and account for memory or recursion depth. Weighted shortest paths require a suitable algorithm beyond ordinary BFS.|Unweighted shortest path;Visited handling;Depth and weighted limits
dsa|Heaps and intervals|How do you solve a top-k problem and an overlap problem?|For top-k, maintain a bounded heap when that meets time and memory constraints, or consider sorting and selection. For intervals, sort by a relevant endpoint and state the overlap convention. Explain whether touching endpoints overlap; correctness depends on the problem's definition.|Heap tradeoffs;Sorting criterion;Endpoint semantics
dsa|Dynamic programming|How do you derive a DP solution rather than memorize one?|Define the state as a sufficient description of a subproblem, derive transitions from choices, specify base cases, and choose a valid evaluation order. Confirm overlapping subproblems and optimal structure. Optimize space only after checking which previous states each transition requires.|State;Transitions and base cases;Dependency order
dsa|Interview execution|What is your process for a unfamiliar coding question?|Clarify constraints and examples, present a correct baseline, and identify a better approach with its invariant. Implement incrementally, test boundaries and failure cases, and explain time and space. If stuck, communicate reasoning and narrow the problem rather than silently guessing.|Clarification;Correctness and complexity;Edge-case testing
`;
const learningBank=learningRows.trim().split('\n').map((row,index)=>{const [track,topic,q,a,points]=row.split('|');return {id:`learn-${track}-${index}`,track,topic,q,a,points:points.split(';'),source:learningSources[track]}});
