// Objective assessment: 1 correct = 1 mark, wrong or skipped = 0; no written answer needed.
const normalizeBeforeQuiz=normalize;normalize=data=>{const result=normalizeBeforeQuiz(data);for(const a of result.learning.attempts){if(a.mode!==undefined&&a.mode!=='mcq')throw Error('Invalid assessment mode');if(a.mode==='mcq'&&a.answers.some(r=>![0,1].includes(r.score)))throw Error('Invalid quiz score');}return result};
startAssessment=questions=>{if(!questions.length){document.querySelector('#learningMessage').textContent='No questions available. Select another platform or scope.';return}if(activeAssessment&&!confirm('Discard this unfinished quiz and start again?'))return;lastAssessmentIds=questions.map(q=>q.id);activeAssessment={questions,index:0,answers:[],selected:null,checked:false,optionOrder:shuffled([0,1,2])};document.querySelector('#learningMessage').textContent='';renderAssessment();document.querySelector('#assessmentPanel').scrollIntoView({behavior:'smooth',block:'start'});document.querySelector('#assessmentPanel').focus()};
renderAssessment=()=>{
 const run=activeAssessment,q=run.questions[run.index],item=objectiveBank.get(q.id),panel=document.querySelector('#assessmentPanel');panel.classList.remove('hidden');
 panel.innerHTML=`<div class="card-title"><p class="label">${run.index+1} / ${run.questions.length} · ${esc(trackNames[q.track])} · 1 MARK</p><button class="ghost small" id="cancelAssessment">End quiz</button></div><h3>${esc(q.q)}</h3><p class="muted">Choose the best answer. Correct = 1 mark; wrong or skipped = 0. No negative marking.</p><fieldset class="mcq-options"><legend>Answer choices</legend>${run.optionOrder.map((choice,i)=>`<label class="mcq-option ${run.checked&&choice===item.correct?'correct':''} ${run.checked&&choice===run.selected&&choice!==item.correct?'incorrect':''}"><input type="radio" name="quiz-choice" value="${choice}" ${run.selected===choice?'checked':''} ${run.checked?'disabled':''}><span class="option-letter">${String.fromCharCode(65+i)}</span><span>${esc(item.choices[choice])}</span></label>`).join('')}</fieldset>${run.checked?`<div class="quiz-feedback" role="status"><strong>${run.selected===item.correct?'Correct · 1/1 mark':run.selected===null?'Skipped · 0/1 mark':'Incorrect · 0/1 mark'}</strong><p><b>Correct answer:</b> ${esc(item.choices[item.correct])}</p><p>${esc(q.a)}</p><a class="table-link" href="${q.source[1]}" target="_blank" rel="noreferrer">Further reading ↗</a></div><button class="primary" id="nextQuiz">${run.index+1===run.questions.length?'Finish and see score':'Next question →'}</button>`:'<div class="rating-actions"><button class="primary" id="checkQuiz" disabled>Check answer</button><button class="ghost" id="skipQuiz">Skip question</button></div>'}`;
 panel.querySelectorAll('[name=quiz-choice]').forEach(input=>input.onchange=()=>{run.selected=Number(input.value);document.querySelector('#checkQuiz').disabled=false});
 document.querySelector('#cancelAssessment').onclick=()=>{if(confirm('End this unfinished quiz without saving it?')){activeAssessment=null;panel.classList.add('hidden')}};
 if(!run.checked){document.querySelector('#checkQuiz').onclick=()=>{if(run.selected===null)return;run.checked=true;renderAssessment()};document.querySelector('#skipQuiz').onclick=()=>{run.selected=null;run.checked=true;renderAssessment()};}
 else document.querySelector('#nextQuiz').onclick=()=>{run.answers.push({id:q.id,response:run.selected===null?'(Skipped)':item.choices[run.selected],score:run.selected===item.correct?1:0});run.index++;if(run.index===run.questions.length)finishAssessment();else{run.selected=null;run.checked=false;run.optionOrder=shuffled([0,1,2]);renderAssessment();panel.focus()}};
};
finishAssessment=()=>{const run=activeAssessment,tracks=[...new Set(run.questions.map(q=>trackNames[q.track]))],attempt={id:crypto.randomUUID(),date:new Date().toLocaleString('en-IN'),mode:'mcq',track:tracks.length===1?tracks[0]:'Mixed tracks',answers:run.answers};state.learning.attempts.push(attempt);for(const r of run.answers)state.learning.ratings[r.id]=r.score===1?2:0;save();activeAssessment=null;const score=run.answers.reduce((n,r)=>n+r.score,0),missed=run.answers.filter(r=>r.score===0);document.querySelector('#assessmentPanel').innerHTML=`<p class="label">QUIZ COMPLETE / AUTOMATIC SCORE</p><h3>${score} / ${run.answers.length} marks · ${Math.round(score/run.answers.length*100)}%</h3><p>${missed.length} wrong or skipped. Previous written/self-scored attempts remain in history with their original scale.</p><div class="rating-actions"><button class="primary" id="retakeSame">Retake this set</button><button class="secondary" id="retakeMissed" ${missed.length?'':'disabled'}>Retake wrong / skipped</button><button class="ghost" id="closeResults">Close results</button></div><div class="quiz-review">${run.answers.map(r=>{const q=learningBank.find(q=>q.id===r.id),key=objectiveBank.get(r.id);return `<details><summary>${r.score?'✓':'×'} ${esc(q.q)} · ${r.score}/1</summary><p>Your choice: ${esc(r.response)}</p><p>Correct: ${esc(key.choices[key.correct])}</p><p>${esc(q.a)}</p></details>`}).join('')}</div>`;document.querySelector('#retakeSame').onclick=()=>startAssessment(shuffled(lastAssessmentIds.map(id=>learningBank.find(q=>q.id===id))));document.querySelector('#retakeMissed').onclick=()=>startAssessment(shuffled(missed.map(r=>learningBank.find(q=>q.id===r.id))));document.querySelector('#closeResults').onclick=()=>document.querySelector('#assessmentPanel').classList.add('hidden');renderLearning();};
document.querySelector('.assessment-setup h3').textContent='One-mark knowledge quiz';document.querySelector('.assessment-setup .muted').textContent='Select an answer; the quiz marks it automatically and explains the correct choice. Each question is worth 1 mark. Retake a full platform, 10 shuffled questions, or previous mistakes. Search only filters the library; topic selection also scopes the quiz.';
document.querySelector('#startAssessment').textContent='Start / retake quiz';document.querySelector('#assessmentScope option[value=weak]').textContent='Previously wrong / partial';
renderLearning();
