// Suggested mobile designs. Protocol journeys show main path; explanations include alternatives.
const mobileSources={architecture:['Android architecture','https://developer.android.com/topic/architecture/recommendations'],ios:['Apple frameworks','https://developer.apple.com/documentation/technologies'],android:['Android fundamentals','https://developer.android.com/guide/components/fundamentals'],rn:['TurboModules','https://reactnative.dev/docs/turbo-native-modules-introduction'],push:['FCM message types','https://firebase.google.com/docs/cloud-messaging/customize-messages/set-message-type'],apns:['APNs registration','https://developer.apple.com/documentation/usernotifications/registering-your-app-with-apns'],mqtt:['MQTT 5 specification','https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html'],ble:['Android BLE','https://developer.android.com/develop/connectivity/bluetooth/ble/ble-overview'],coreble:['Core Bluetooth','https://developer.apple.com/documentation/corebluetooth'],work:['WorkManager','https://developer.android.com/topic/libraries/architecture/workmanager'],links:['App Links','https://developer.android.com/training/app-links'],purchases:['StoreKit entitlements','https://developer.apple.com/documentation/storekit/transaction/currententitlements'],upgrade:['RN upgrades','https://reactnative.dev/docs/upgrading'],firebase:['Firebase / BoM','https://firebase.google.com/docs/android/setup'],security:['Native OAuth / PKCE','https://www.rfc-editor.org/rfc/rfc8252'],background:['BackgroundTasks','https://developer.apple.com/documentation/backgroundtasks'],camera:['CameraX','https://developer.android.com/media/camera/camerax']};
const mobileFlowBank=[];
// id|title|group|track|source|nodes|explanations|pitfall|exercise
function addMobileFlows(content){content.trim().split('\n').forEach(line=>{const parts=line.split('|');if(parts.length!==9)throw Error('Invalid flow '+parts[0]);const [id,title,group,track,source,journey,explanation,pitfall,exercise]=parts,nodes=journey.split(';'),steps=explanation.split(';');mobileFlowBank.push({id,title,group,track,source,note:steps[0],rows:nodes.map(n=>[n]),edges:nodes.slice(1).map((_,i)=>[i,i+1]),steps,pitfall,exercise});});}
addMobileFlows(`
mvvm|MVVM: event to observable state|Architecture|architecture|architecture|View action;ViewModel validates intent;Use case / repository;Domain result / error;Map observable UI state;View renders state|Keep services behind contracts.;Test loading, empty, success and error.;Cancel or reject stale requests.;Publish through the UI isolation boundary.|A ViewModel is not durable storage and should not retain a screen.|Build a searchable list with delayed-response tests.
viper|VIPER: responsibilities and routing|Architecture|ios|ios|View → Presenter;Presenter → Interactor;Interactor → data gateway;Entity result → Presenter;Presenter → View model;Presenter → Router if navigating|View renders, Presenter prepares display state.;Interactor owns use cases, Entity describes domain data.;Router assembles navigation and dependencies.;This is a design suggestion, not an Apple requirement.|Many protocols for a small feature can hide behavior.|Test checkout Interactor without UIKit.
mvi|MVI / reducer: state transitions|Architecture|architecture|architecture|UI intent;Effect handler;Outcome action;Pure reducer;New immutable state;UI renders|Keep network/disk effects outside reducers.;Define loading, result and error actions.;Scope effects to the lifecycle.;Plan one-time navigation handling.|Replayed navigation can open a screen twice.|Implement deterministic retry transitions.
clean|Clean architecture: dependency direction|Architecture|architecture|architecture|Presentation calls use case;Use case uses domain port;Repository implements port;Adapter calls API / DB;Map to domain result;Return to presentation|Call arrows differ from source dependencies, which point toward domain contracts.;Keep DTOs out of business rules.;Inject implementations at composition root.;Add layers for useful policy.|Wrapping every getter adds little value.|Swap fake and API repositories without editing domain rules.
coordinator|Coordinator: navigation ownership|Architecture|ios|ios|Validated navigation event;Coordinator selects route;Build feature dependencies;Present destination;Receive result / cancel;Release child feature|Separate route parsing from authorization.;Retain child flows only while active.;Return semantic results.;Support back, dismissal and restoration.|Strong closures can retain finished screens.|Implement login cancellation and verify deallocation.
modular|Feature modules and injection|Architecture|android|architecture|Composition root;Scoped dependencies;Feature interface;Internal use case / adapters;Stable feature result;Dispose feature scope|Define ownership and public interfaces.;Limit module dependencies.;Choose app, session and feature lifetimes.;Build features independently where useful.|Service locators hide dependencies.|Extract profile and draw its dependency graph.
push-apns|iOS push: registration to tap|Connectivity|ios|apns|Explain notification value;Request alert permission;Register with APNs;Send fresh token to backend;Provider → APNs → device;Tap → authorize → fetch|Alert permission differs from APNs registration.;Associate current app/device tokens with account.;Provider credentials stay on backend, handle invalid tokens.;Delivery is best effort, fetch current data on activation.|Token is not a login credential, unlink on logout.|Test denial, token change and signed-out tap.
push-fcm|Android / RN push: FCM|Connectivity|android|push|Check permission / channels;Receive refreshed FCM token;Register installation;Backend sends message;OS display / app callback;Tap / callback → reconcile|Android 13+ runtime notification permission affects display.;Payload/app state change callback behavior.;Use trusted server HTTP v1/Admin SDK.;RN needs compatible native integration/binary.|Accepted send does not prove user delivery.|Test notification-only, data-only and mixed payloads.
push-silent|Silent push: refresh hint|Connectivity|ios|background|Server data changes;Send background hint;OS may grant execution;Fetch authorized delta;Persist / finish;Reconcile next launch|Use durable server cursors.;Background pushes can be throttled or omitted.;Finish within granted budget.;Recover missed data on activation.|Not a guaranteed job timer.|Drop three pushes then catch up on app launch.
`);
addMobileFlows(`
mqtt-connect|MQTT: connect, subscribe, publish|Connectivity|architecture|mqtt|Network / lifecycle permit;TLS + broker authentication;CONNECT → CONNACK;SUBSCRIBE → SUBACK;PUBLISH → subscriber;Apply domain event|Authorize broker topic access.;Choose QoS and session policy.;Validate payload and deduplicate effects.;Bound buffers, reconnect with jitter.|Suspension can stop an assumed permanent socket.|Reconnect a foreground sensor dashboard after airplane mode.
mqtt-qos|MQTT QoS: delivery semantics|Connectivity|architecture|mqtt|Choose QoS 0 / 1 / 2;Publish packet;QoS 0: no publish ACK;QoS 1: PUBACK;QoS 2: REC / REL / COMP;Deduplicate business effects|QoS nodes compare alternatives, not consecutive stages.;QoS 0: at most once, 1: at least once, 2: exactly once at protocol receiver.;QoS 2 does not make downstream business transactions globally exactly once.;Persist event IDs across restarts.|Protocol guarantees do not replace database idempotency.|Replay one event twice, apply its change once.
mqtt-session|MQTT: session, retained state, Will|Connectivity|architecture|mqtt|Detect disconnect;Backoff + authentication;Resume / create session;Restore subscriptions;Reconcile retained / live data;Show online / stale state|MQTT 5 Clean Start/Session Expiry control continuation.;Retained messages are latest topic snapshots, not history.;Use message expiry and timestamps.;Will reports unexpected disconnect under its policy.|Retained commands can repeat for new subscribers.|Compare retained temperature with non-retained commands.
ble-central|BLE central: discovery to notify|Connectivity|architecture|ble|Check adapter + permission;Filtered scan + timeout;Select peripheral / connect;Discover GATT attributes;Read / write / enable notify;Decode → domain state|Stop unnecessary scanning.;Serialize GATT operations and handle timeout.;Android notify needs local enablement plus matching CCCD write.;iOS uses Core Bluetooth subscription callbacks.|Connected does not mean expected characteristics exist.|Read battery data and recover from missing services.
ble-peripheral|BLE peripheral: advertise service|Connectivity|ios|coreble|Define GATT schema;Create peripheral / server;Advertise when permitted;Central connects / subscribes;Validate requests;Send bounded updates|Support depends on device/platform.;Version properties and encoding.;Respect subscription/backpressure.;Require appropriate pairing/app authorization.|Advertising is discovery, not trusted identity.|Build a temperature peripheral with read and notify.
ble-background|BLE lifecycle and restoration|Connectivity|architecture|ble|App leaves foreground;Evaluate work policy;Persist logical session;Supported background path;Restore / reconnect if allowed;Reconcile on activation|Android companion-device/foreground-service paths depend on use case.;iOS modes/restoration have limits.;No guaranteed unlimited scans or permanent process.;Allow manual recovery.|Restoration does not guarantee continuous sampling.|Test screen-off, reboot, process death and peripheral power loss.
ble-packets|BLE packet framing and commands|Connectivity|architecture|ble|Version command;Split to reported payload limit;Queue writes / responses;Reassemble bounded message;Validate ID / length / integrity;Apply once + return result|Use platform/negotiated payload limits.;Define framing, sequence IDs and timeouts.;Pairing differs from application authorization.;Bound reassembly memory.|Write callback may confirm transport, not command completion.|Drop a middle fragment and recover safely.
websocket|WebSocket: realtime with replay|Connectivity|architecture|android|Authenticate secure handshake;Subscribe with cursor;Receive events;Validate / deduplicate / persist;Disconnect → jittered retry;Replay or fetch snapshot|Define heartbeat/timeout policy.;Cursors cover missed events.;Bound buffers and batch UI work.;Fetch on activation after suspension.|Reconnect without replay can lose messages.|Reconcile chat after two minutes offline.
login-pkce|OAuth login with PKCE|App journeys|architecture|security|Create verifier / challenge;Open system authorization agent;Validate redirect + state;Exchange code + verifier;Securely store session;Fetch authorized profile|Use approved system browser/agent.;Keep client secrets off device.;Validate redirect binding and cancellation.;Separate refresh, storage and sign-out.|Shipped client secrets cannot protect public native apps.|Reject incorrect state and expired authorization codes.
logout|Logout and account switching|App journeys|architecture|security|User chooses sign-out;Cancel account work;Revoke server session if supported;Clear tokens / private cache;Unlink push / socket identity;Render signed-out state|Server revoke and local clearing fail independently.;Session generation rejects old async responses.;Define unsynced-change policy.;Separate public and account data.|Late account A results must not update account B.|Switch users during a delayed request.
deep-link|Deep links: cold start and auth gate|App journeys|architecture|links|OS resolves verified link;Parse allowlisted route;Validate parameters;Restore app / session;Authorize requested resource;Navigate / safe fallback|Configure Universal Links/App Links association.;Handle initial and running-app URLs.;Keep pending route through login without repeat.;Backend enforces access.|Resource ID in a link does not grant access.|Test malformed, signed-out and deleted-resource links.
permission|Permission denial and recovery|App journeys|architecture|android|User starts feature;Explain needed capability;Check platform status;Request if eligible;Granted → perform work;Denied → fallback / settings|Ask in context.;Handle limited/approximate access.;Support revocation and settings recovery.;Rules vary with OS and target level.|Repeated prompts without fallback create dead ends.|Test camera denial, later grant and revocation.
pagination|Cursor pagination and query identity|App journeys|architecture|architecture|Load first page / cache;Store query ID + cursor;Request next page once;Validate generation;Merge stable item IDs;End or retry cursor|Keep state per filter/search.;Reject old-generation responses.;Preserve stable keys/scroll.;Separate empty/end from errors.|Offset pages can shift when data changes.|Change filters while page two is loading.
optimistic|Optimistic edits and conflicts|App journeys|architecture|architecture|Write pending local action;Render optimistic state;Send ID + base version;Server accepts / conflicts;Commit or merge result;Expose unresolved recovery|Persist durable operations.;Use server idempotency/version contracts.;Define rejection reconciliation.;Show non-mergeable conflicts.|Blind mutation retries can duplicate effects.|Like a post offline then reconcile rejection.
upload|Resumable upload and cancellation|App journeys|architecture|android|Select / validate file;Create authorized session;Send bounded chunks;Persist acknowledged offsets;Finalize backend result;Update UI / cancel|Signed URLs expire and need scoped renewal.;Resume only where transport supports it.;Define checksums/limits/orphan cleanup.;Use supported background transfer APIs.|100% sent bytes do not prove backend finalization.|Restart during upload and resume without duplication.
cache-image|Image loading and memory budget|App journeys|architecture|android|Visible item requests image;Memory / disk lookup;Fetch with cancellation;Downsample / decode;Publish to matching item;Evict under budget|Key cache by transform/version.;Decode for display size.;Cancel offscreen work.;Measure decode cost and memory pressure.|Recycled cells can show stale delayed images.|Fast-scroll large photos on a slow network.
subscriptions|Subscriptions and entitlements|App journeys|architecture|purchases|Load store products;User purchases;Verified / pending result;Grant valid entitlement;Acknowledge / finish;Observe renewal / refunds|StoreKit and Play Billing have distinct contracts.;Server verification/events help maintain access.;Handle cancel, pending, restore and expiry.;Acknowledge Play purchases where required, finish Apple after processing.|Client booleans miss fraud and refunds.|Test purchase, pending, restore and expiry in sandbox.
location|Location: accuracy and battery|App journeys|architecture|android|User starts feature;Request suitable access;Choose accuracy / interval;Receive timestamped samples;Reject stale / poor samples;Stop / change work policy|Use foreground access when sufficient.;Background access has separate platform rules.;Choose coarse/batched updates where useful.;Offer clear stop control.|Maximum accuracy/frequency drains power.|Compare route quality and battery for two intervals.
`);
addMobileFlows(`
swift-task|Swift tasks: cancellation and isolation|Native platform|ios|ios|Screen starts scoped Task;Await repository operation;Actor protects shared state;Check cancellation / request ID;MainActor publishes UI state;Exit cancels owned work|Await does not imply background-thread execution.;Actors can interleave across suspension.;Tie work lifetime to the feature.;Place CPU work deliberately.|Long-lived strong captures retain screens.|Cancel search and prove no stale update.
kotlin-flow|Kotlin coroutines and lifecycle flow|Native platform|android|architecture|UI action;ViewModel coroutine;Repository suspend / Flow;Map result to UI state;StateFlow emits state;Lifecycle-aware collection|Avoid blocking main thread.;Do not swallow cancellation as a domain error.;Collect UI with lifecycle awareness.;Persist durable data outside ViewModel.|Catching all Throwable can swallow cancellation.|Stop/restart a Room-backed screen.
swift-persist|SwiftData / Core Data boundaries|Native platform|ios|ios|Open compatible store;Context-bound operation;Fetch / edit model;Save / rollback;Publish mapped snapshot;Migrate existing stores|Respect context/isolation contracts.;Surface save failures.;Design relationship/delete rules.;Map objects carefully across concurrency.|Clean installs do not test old-store migrations.|Migrate an old fixture and verify relationships.
room-migration|Room reactive reads and migration|Native platform|android|architecture|Versioned entities;DAO transaction;Query invalidation;Flow emits mapped result;UI renders state;Validate migration path|Match indexes to queries.;Export schemas and test old databases.;Transact related writes.;Room is not automatic encryption or cloud sync.|Destructive fallback can erase user records.|Add a non-null column to a populated old schema.
workmanager|Android durable background work|Native platform|android|work|Persist pending operation;Unique constrained work;OS schedules execution;Cancellable worker runs;Success / retry / failure;Observe durable outcome|Use for deferrable persistent work, not exact timers.;Make retries idempotent.;Check long-running/foreground policy.;Scope work to the right account.|Scheduling does not guarantee exact start time.|Queue a network-constrained upload without duplicates.
ios-background|iOS background tasks and transfers|Native platform|ios|background|Choose supported API;Declare / register capability;Submit task / transfer;System grants execution;Expiration → save progress;Finish / reconcile launch|BGTaskScheduler execution is discretionary.;Background URLSession supports eligible transfers.;Cancel and persist on expiration.;No general-purpose permanent process.|Earliest start is not a precise alarm.|Test expiration and unfinished-transfer relaunch.
rn-turbo|RN TurboModule typed native boundary|Native platform|rn|rn|Define typed spec;Codegen interfaces;Implement native module;Register / build binary;Invoke / receive events;Dispose listeners / resources|Check installed architecture/toolchain.;Codegen does not replace validation.;Define thread/queue ownership.;Native changes require compatible builds.|Synchronous JSI can still block or race.|Expose device info and test teardown/invalid input.
camera|Camera capture and lifecycle|Native platform|architecture|camera|Permission check;Lifecycle-bound preview;Capture media;Process off UI path;Store / upload by user intent;Release resources|CameraX/AVFoundation have different session APIs.;Handle interruption/orientation.;Bound frame buffers.;Define metadata and temporary-file cleanup.|Leaked sessions drain power and block camera reuse.|Rotate, background and test low-storage capture.
crash|Crash and performance observability|SDK / delivery|architecture|firebase|Consent-aware initialization;Attach exact release context;Capture crash / latency;Upload symbols / maps;Alert meaningful regression;Fix / staged verification|Use correctly matched symbols/source maps.;Redact sensitive data.;Track meaningful user transactions.;Attach OS/device/dependency versions.|Missing maps hide minified RN stack detail.|Confirm a symbolicated test crash.
flags|Remote configuration and kill switch|SDK / delivery|architecture|firebase|Safe bundled defaults;Fetch scoped config;Validate values;Activate at chosen boundary;Watch cohort outcomes;Disable / recover|Flags cannot install absent native code.;Keep schemas compatible with old apps.;Choose startup/session activation.;Test offline defaults and combinations.|Fetch and activation are separate operations.|Test a default-off feature with no network.
sdk-evaluate|Select a third-party SDK|SDK / delivery|staff|firebase|Define capability constraints;Inspect maintenance / license;Check native compatibility;Review data / permissions;Prototype cost / failure;Pin approved dependency|Compare platform APIs first.;Check min OS, RN architecture and footprint.;Wrap vendor behind an adapter.;Record ownership and removal plan.|Popularity does not prove compatibility.|Compare BLE options on a real device.
sdk-upgrade|SDK upgrade: notes to rollout|SDK / delivery|staff|upgrade|Inventory exact versions;Read migration / security notes;Update compatible pinned set;Adapt APIs / configuration;Test device / data matrix;Stage / monitor / recover|Classify source, binary, behavior, data and privacy changes.;Keep lockfiles/builds reproducible.;Inspect transitive dependencies.;Data migrations may not be reversible by binary rollback.|A clean build does not prove behavioral compatibility.|Upgrade one library with before/after checks.
ios-upgrade|iOS SDK and deployment target|SDK / delivery|ios|ios|Read Xcode / SDK notes;Audit availability / deprecation;Update signing / capabilities;Guard newer APIs;Archive / old-data tests;Release and watch metrics|Compile SDK differs from minimum OS.;Test oldest supported runtime.;Audit required privacy manifests/signatures.;Exercise push, StoreKit and scene behavior.|Raising minimum OS excludes users.|Build with new SDK and test oldest supported OS.
android-upgrade|Android target SDK and toolchain|SDK / delivery|android|android|Read behavior-change guides;Check AGP / Gradle / JDK;Update compile / target;Adapt permissions / work;Test old + new OS;Stage with diagnostics|compileSdk, targetSdk and minSdk differ.;Audit services, notifications and large screens.;Check native-library/build requirements.;Test installation upgrades with old data.|targetSdk can change runtime behavior without source changes.|Test one target-specific change and denial recovery.
rn-upgrade|React Native / Expo upgrade|SDK / delivery|rn|upgrade|Record supported version matrix;Read upgrade diff;Align modules / toolchains;Regenerate / build native code;Test release critical paths;Ship compatible binary|Expo SDK specifies compatible combinations.;Check native dependencies, Hermes and codegen.;Debug success does not prove release behavior.;OTA must match installed runtime and policy.|JS updates cannot add absent native modules.|Test startup, navigation, BLE and push in release mode.
ci-release|Mobile CI: signing to staged release|SDK / delivery|staff|architecture|Locked dependencies / toolchain;Tests / native builds;Sign with managed credentials;Upload symbols and artifact;Store review / rollout cohort;Monitor / pause / recover|Keep credentials outside source.;Tie symbols to exact delivered builds.;Exercise clean installs and upgrades.;Maintain backward-compatible backend contracts.|A kill switch cannot replace installed native binaries.|Create a signed release checklist with recovery owners.
`);
architectureDiagrams.forEach(d=>{d.group='Original system designs';d.source=d.id==='rn'?'rn':d.id==='ios'?'ios':'architecture'});
architectureDiagrams.push(...mobileFlowBank);
const flowPanel=document.querySelector('#architectureSelect').closest('.card');
flowPanel.querySelector('.guide-label').before(Object.assign(document.createElement('div'),{className:'guide-controls',innerHTML:'<label class="guide-label">Find a mobile flow<input id="mobileFlowSearch" type="search" placeholder="MVVM, VIPER, push, MQTT, BLE…"></label><label class="guide-label">Area<select id="mobileFlowGroup"><option value="">All areas</option>'+[...new Set(architectureDiagrams.map(d=>d.group))].map(g=>`<option>${esc(g)}</option>`).join('')+'</select></label>'}));
let mobileFlowStep=0;
const previousArchitectureRenderer=renderArchitecture;
renderArchitecture=function(){const d=architectureDiagrams.find(d=>d.id===document.querySelector('#architectureSelect').value);if(!d){document.querySelector('#architectureGuide').innerHTML='<p class="muted" role="status">No matching flows. Clear the search or choose another area.</p>';return}mobileFlowStep=Math.min(mobileFlowStep,d.steps.length-1);previousArchitectureRenderer();const guide=document.querySelector('#architectureGuide');guide.insertAdjacentHTML('afterbegin',`<p class="label">${esc(d.group)} · ${mobileFlowStep+1} / ${d.steps.length} explanation steps</p>`);guide.querySelectorAll('.guide-explanation li').forEach((li,i)=>li.classList.toggle('mobile-active-step',i===mobileFlowStep));guide.insertAdjacentHTML('beforeend',`<div class="rating-actions"><button class="secondary small" id="flowPrevious" ${mobileFlowStep===0?'disabled':''}>← Previous explanation</button><button class="primary small" id="flowNext" ${mobileFlowStep===d.steps.length-1?'disabled':''}>Next explanation →</button><button class="ghost small" id="flowRestart">Restart</button></div><p class="active-step" role="status">${esc(d.steps[mobileFlowStep])}</p>${d.pitfall?`<div class="flow-practice"><h4>Common mistake</h4><p>${esc(d.pitfall)}</p><h4>Build / test it</h4><p>${esc(d.exercise)}</p></div>`:''}<p><a class="table-link" href="${mobileSources[d.source][1]}" target="_blank" rel="noreferrer">${esc(mobileSources[d.source][0])} ↗</a></p><button class="secondary small" id="copyFlowLink">Copy link to this flow</button><span id="flowLinkStatus" role="status"></span>`);document.querySelector('#flowPrevious').onclick=()=>{mobileFlowStep--;renderArchitecture()};document.querySelector('#flowNext').onclick=()=>{mobileFlowStep++;renderArchitecture()};document.querySelector('#flowRestart').onclick=()=>{mobileFlowStep=0;renderArchitecture()};document.querySelector('#copyFlowLink').onclick=async()=>{const link=new URL(location.href);link.hash='visuals/'+d.id;try{await navigator.clipboard.writeText(link.href);document.querySelector('#flowLinkStatus').textContent=' Link copied'}catch{document.querySelector('#flowLinkStatus').textContent=' '+link.href}};};
function matchesMobileQuery(text,query){const content=text.toLowerCase(),words=content.split(/[^a-z0-9]+/);return query.trim().split(/\s+/).filter(Boolean).every(term=>term.length<=3?words.includes(term):content.includes(term));}
function filterMobileFlows(){const q=document.querySelector('#mobileFlowSearch').value.toLowerCase(),group=document.querySelector('#mobileFlowGroup').value,select=document.querySelector('#architectureSelect'),old=select.value;const list=architectureDiagrams.filter(d=>(!group||d.group===group)&&matchesMobileQuery(`${d.title} ${d.group} ${d.note} ${d.steps.join(' ')}`,q));select.innerHTML=list.map(d=>`<option value="${d.id}">${esc(d.title)}</option>`).join('');if(list.some(d=>d.id===old))select.value=old;mobileFlowStep=0;renderArchitecture();}
function openMobileFlow(id,scroll=true){if(!architectureDiagrams.some(d=>d.id===id))return;document.querySelector('#mobileFlowSearch').value='';document.querySelector('#mobileFlowGroup').value='';filterMobileFlows();document.querySelector('#architectureSelect').value=id;mobileFlowStep=0;renderArchitecture();if(scroll)document.querySelector('#visuals').scrollIntoView({block:'start'});}
document.querySelector('#mobileFlowSearch').oninput=filterMobileFlows;document.querySelector('#mobileFlowGroup').onchange=filterMobileFlows;document.querySelector('#architectureSelect').onchange=()=>{mobileFlowStep=0;renderArchitecture()};
document.querySelector('#visuals .section-note').textContent=`${architectureDiagrams.length} mobile / system flows · ${dsaVisuals.length} DSA guides`;
flowPanel.insertAdjacentHTML('afterbegin','<h3>Mobile flow library</h3><p class="muted">Suggested designs and protocol learning journeys. Arrows show the main path; alternatives, recovery and platform limits are explained beside each diagram.</p><div class="flow-shortcuts">'+['mvvm','viper','push-apns','push-fcm','mqtt-connect','ble-central','sdk-upgrade'].map(id=>`<a class="secondary small" href="#visuals/${id}">${esc(architectureDiagrams.find(d=>d.id===id).title.split(':')[0])}</a>`).join('')+'</div>');
function routeMobileFlow(){if(location.hash.startsWith('#visuals/'))openMobileFlow(decodeURIComponent(location.hash.slice(9)))}
window.addEventListener('hashchange',routeMobileFlow);filterMobileFlows();routeMobileFlow();
// SDK options are learning suggestions, not a claim that every library fits every app.
const mobileSDKs=`
iOS|SwiftUI / UIKit|Screen state, layout and navigation|API availability, lifecycle, accessibility and minimum OS|mvvm|https://developer.apple.com/documentation/swiftui|Platform framework
iOS|URLSession|HTTP requests and supported background transfers|Cancellation, cache policy, ATS and transfer restoration|upload|https://developer.apple.com/documentation/foundation/urlsession|Platform framework
iOS|SwiftData / Core Data|Local model persistence|Schema migration, context isolation and existing-store tests|swift-persist|https://developer.apple.com/documentation/swiftdata|Platform framework
iOS|UserNotifications / APNs|Local and remote notification integration|Permission, token changes, capabilities and payload routing|push-apns|https://developer.apple.com/documentation/usernotifications|Platform framework
iOS|Core Bluetooth|BLE central/peripheral interaction|Usage declarations, background modes and GATT lifecycle|ble-central|https://developer.apple.com/documentation/corebluetooth|Platform framework
iOS|StoreKit|In-app purchases and subscriptions|Verified transactions, entitlement changes and restore|subscriptions|https://developer.apple.com/documentation/storekit|Platform framework
iOS|BackgroundTasks|Discretionary background processing|Registration, expiration and supported task types|ios-background|https://developer.apple.com/documentation/backgroundtasks|Platform framework
iOS|AVFoundation / Core Location|Camera/media or location capabilities|Permissions, interruptions, energy and resource cleanup|camera|https://developer.apple.com/documentation/avfoundation|Platform framework
Android|Compose / Lifecycle|Declarative UI and observable screen state|Kotlin/compiler compatibility, state saving and lifecycle collection|kotlin-flow|https://developer.android.com/develop/ui/compose|Platform library
Android|Room / DataStore|Structured records or small preference state|Migrations, transaction boundaries and appropriate storage choice|room-migration|https://developer.android.com/training/data-storage/room|Platform library
Android|Hilt|Dependency injection and scoped lifetimes|Plugin alignment, worker injection and scope ownership|modular|https://developer.android.com/training/dependency-injection/hilt-android|Platform library
Android|WorkManager|Deferrable persistent background work|Constraints, retries, worker factories and scheduling limits|workmanager|https://developer.android.com/topic/libraries/architecture/workmanager|Platform library
Android|CameraX / location APIs|Lifecycle-aware capture or location features|Device capabilities, permission and background policy|camera|https://developer.android.com/media/camera/camerax|Platform library
Android|Play Billing|Purchases and subscriptions|Required library support, pending purchases and acknowledgement|subscriptions|https://developer.android.com/google/play/billing/integrate|Platform library
Android|Nordic Android BLE Library|Optional queued GATT integration|Read version-specific support, scanning is separate in this library, test real devices|ble-central|https://github.com/nordicsemi/Android-BLE-Library|Optional third-party
React Native|React Navigation|Navigation and deep-link integration|Native dependencies, restoration and current upgrade guide|deep-link|https://reactnavigation.org/docs/getting-started/|Optional third-party
React Native|Reanimated|Animations and worklets|RN architecture compatibility, native build and worklet configuration|rn-upgrade|https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/|Optional third-party
React Native|TanStack Query|Server-state fetching and cache coordination|AppState/network integration, stale policy and account cache isolation|pagination|https://tanstack.com/query/latest/docs/framework/react/react-native|Optional third-party
React Native|React Native Firebase|Native Firebase integrations|RN/native Firebase version alignment, platform files and rebuilt binary|push-fcm|https://rnfirebase.io/|Optional third-party
React Native|react-native-ble-plx|Optional native BLE central integration|OS permissions, connection lifecycle and installed architecture support|ble-central|https://github.com/dotintent/react-native-ble-plx|Optional third-party
React Native|Expo modules / SDK|Native capability modules in compatible Expo projects|Expo-supported versions, config plugins and development builds|rn-upgrade|https://docs.expo.dev/versions/latest/|Framework ecosystem
Cross-platform|Firebase Crashlytics / Remote Config|Crash diagnostics or remotely controlled behavior|Android BoM alignment, symbols/maps, defaults and privacy|crash|https://firebase.google.com/docs/android/setup|Service SDK
Cross-platform|HiveMQ MQTT Client / mqtt-nio|JVM/Android or Swift MQTT implementation candidates|Protocol version, TLS, platform support and mobile lifecycle, not an RN drop-in|mqtt-connect|https://github.com/hivemq/hivemq-mqtt-client|Optional third-party
Cross-platform|Platform HTTP / WebSocket APIs|Network transport before extra dependencies|Timeouts, reconnect, auth, cancellation and foreground/background behavior|websocket|https://developer.apple.com/documentation/foundation/urlsession|Platform framework
`.trim().split('\n').map(row=>{const [platform,name,use,check,flow,url,type]=row.split('|');return {platform,name,use,check,flow,url,type};});
const sdkSection=document.createElement('section');sdkSection.id='mobile-sdks';sdkSection.className='section';sdkSection.innerHTML=`<div class="section-head"><div><p class="eyebrow">SDK FIELD GUIDE / REVIEWED 04 OCT 2026</p><h2>Choose the capability. Check the compatibility.</h2></div><p class="section-note">${mobileSDKs.length} SDK / framework options</p></div><p class="muted">Start with platform APIs, then add libraries for a clear requirement. These suggestions link to maintainer documentation; exact package versions depend on your project. Release notes and migration guides are the source of truth for each upgrade.</p><div class="guide-controls"><label class="guide-label">Platform<select id="sdkPlatform"><option value="">All platforms</option>${[...new Set(mobileSDKs.map(s=>s.platform))].map(p=>`<option>${esc(p)}</option>`).join('')}</select></label><label class="guide-label">Search SDKs<input id="sdkSearch" type="search" placeholder="BLE, notification, storage, animation…"></label></div><p id="sdkCount" class="muted" role="status"></p><div id="sdkCards" class="sdk-grid"></div><div class="card v2panel"><h3>A repeatable SDK change checklist</h3><ol class="guide-explanation"><li>Record installed versions, lockfiles, native build tools, minimum OS and target SDK.</li><li>Read release notes: mark API removals, runtime behavior, data migrations, permissions and privacy changes.</li><li>Check platform/RN/Expo compatibility and transitive dependencies. Update one coherent dependency set.</li><li>Rebuild release binaries. Test old data, clean install, denied permissions, offline, account switch and background recovery.</li><li>Ship a small cohort, monitor crashes and core transactions, and define a recovery that keeps stored data compatible.</li></ol><div class="flow-shortcuts"><a class="secondary small" href="#visuals/sdk-upgrade">General SDK upgrade flow</a><a class="secondary small" href="#visuals/ios-upgrade">iOS changes</a><a class="secondary small" href="#visuals/android-upgrade">Android changes</a><a class="secondary small" href="#visuals/rn-upgrade">RN / Expo changes</a><a class="secondary small" href="#updates">Latest platform snapshot</a></div><p class="muted">For Apple submissions, review <a class="table-link" href="https://developer.apple.com/support/third-party-SDK-requirements/" target="_blank" rel="noreferrer">third-party SDK requirements ↗</a>. For Swift MQTT, inspect <a class="table-link" href="https://github.com/sroebert/mqtt-nio" target="_blank" rel="noreferrer">mqtt-nio ↗</a> alongside your deployment/toolchain constraints.</p></div></section>`;
document.querySelector('#visuals').after(sdkSection);
function renderSDKs(){const platform=document.querySelector('#sdkPlatform').value,q=document.querySelector('#sdkSearch').value.toLowerCase(),list=mobileSDKs.filter(s=>(!platform||s.platform===platform)&&matchesMobileQuery(`${s.name} ${s.use} ${s.check} ${s.type}`,q));document.querySelector('#sdkCount').textContent=`${list.length} / ${mobileSDKs.length} options`;document.querySelector('#sdkCards').innerHTML=list.length?list.map(s=>`<article class="card v2panel sdk-card"><p class="label">${esc(s.platform)} · ${esc(s.type)}</p><h3>${esc(s.name)}</h3><p>${esc(s.use)}</p><h4>Before adopting / upgrading</h4><p class="muted">${esc(s.check)}</p><div class="flow-shortcuts"><a class="table-link" href="${s.url}" target="_blank" rel="noreferrer">Official / maintainer docs ↗</a><a class="secondary small" href="#visuals/${s.flow}">See related flow →</a></div></article>`).join(''):'<p class="muted">No matches. Clear the search or choose another platform.</p>';}
document.querySelector('#sdkPlatform').onchange=renderSDKs;document.querySelector('#sdkSearch').oninput=renderSDKs;renderSDKs();
document.querySelector('.hero-actions').insertAdjacentHTML('beforeend','<a class="secondary" href="#mobile-sdks">Mobile SDK guide →</a>');
// Explicit branches for decisions that are central to these journeys.
const mobileBranches={
 permission:{rows:[['User starts permission feature'],['Explain and check status'],['Permission granted?'],['Yes: perform operation','No: fallback / settings'],['Observe result','Recover when access changes']],edges:[[0,1],[1,2],[2,3,'yes'],[2,4,'no'],[3,5],[4,6]],decision:2},
 subscriptions:{rows:[['User starts store purchase'],['Inspect transaction result'],['Verified entitlement?'],['Yes: process and grant','Pending / cancelled / invalid'],['Finish / acknowledge correctly','Wait / show safe outcome'],['Observe later store changes']],edges:[[0,1],[1,2],[2,3,'yes'],[2,4,'no / pending'],[3,5],[4,6],[5,7],[6,7]],decision:2},
 'sdk-upgrade':{rows:[['Read changes / version matrix'],['Update pinned dependency set'],['Adapt APIs and configuration'],['Build + device/data tests pass?'],['Yes: staged rollout','No: fix / keep prior version'],['Monitor + compatible recovery','Repeat validation before shipping']],edges:[[0,1],[1,2],[2,3],[3,4,'yes'],[3,5,'no'],[4,6],[5,7]],decision:3},
 'ble-central':{rows:[['Adapter + permission check'],['Filtered scan / connect'],['Expected services available?'],['Yes: queue GATT operations','No: disconnect / explain'],['Read / write / subscribe','User retry / device recovery'],['Decode + display updates']],edges:[[0,1],[1,2],[2,3,'yes'],[2,4,'no'],[3,5],[4,6],[5,7]],decision:2},
 optimistic:{rows:[['Persist action + render optimistic'],['Send operation ID + base version'],['Server accepts current version?'],['Yes: commit server result','No: reject / conflict'],['Clear pending operation','Merge / rollback / ask user'],['Render reconciled state']],edges:[[0,1],[1,2],[2,3,'yes'],[2,4,'no'],[3,5],[4,6],[5,7],[6,7]],decision:2}
};
Object.entries(mobileBranches).forEach(([id,layout])=>Object.assign(architectureDiagrams.find(d=>d.id===id),layout));renderArchitecture();

document.addEventListener('click',event=>{const link=event.target.closest('a[href^="#visuals/"]');if(link)openMobileFlow(decodeURIComponent(link.getAttribute('href').slice(9)));});
sdkSection.querySelector('.guide-controls').insertAdjacentHTML('beforebegin','<div class="card v2panel"><h3>Suggested learning order</h3><ol class="guide-explanation"><li><strong>Core first:</strong> MVVM/UDF, state ownership, networking, persistence, cancellation and dependency boundaries.</li><li><strong>Production journeys:</strong> login, deep links, permissions, push, pagination, uploads and offline recovery.</li><li><strong>Device / realtime specialization:</strong> BLE central/peripheral, packet framing, MQTT sessions/QoS and WebSocket replay. Use real-device failure tests.</li><li><strong>Staff-level delivery:</strong> explain tradeoffs, modularize one feature, validate SDK migrations, add observability and stage releases.</li></ol><p class="muted">Use VIPER when its explicit responsibilities suit the team and feature. Learn enough to compare its cost with MVVM or reducer-based designs rather than forcing one pattern everywhere.</p></div>');
