// V2 extends the original dashboard and retains its storage key for migration.
const localDay=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dayDate=s=>new Date(`${s}T12:00:00`);
const shiftDay=(s,n)=>{const d=dayDate(s);d.setDate(d.getDate()+n);return localDay(d)};
const monday=s=>shiftDay(s,-((dayDate(s).getDay()+6)%7));
const stages=['Applied','Recruiter','Screening','Technical','Onsite','Offer','Closed'];
const v2defaults=()=>({sessions:[],reviews:{},targets:{role:'Staff Mobile Engineer',salary:'',currency:'INR',location:'',hours:12,exam:''},weekKey:monday(localDay()),weekHistory:{}});
const originalBase=baseState;
baseState=()=>({...originalBase(),...v2defaults(),version:2});
function normalize(data){
 if(!data||typeof data!=='object'||Array.isArray(data))throw Error('Invalid backup');
 if(!Array.isArray(data.weekly)||!Array.isArray(data.applications)||!data.roadmap||!data.checks)throw Error('Not a Career OS backup');
 const result={...baseState(),...data,version:2};
 for(const key of ['roadmap','checks','reviews','targets','weekHistory'])if(!result[key]||typeof result[key]!=='object'||Array.isArray(result[key]))throw Error(`Invalid ${key}`);
 result.targets={...v2defaults().targets,...result.targets};
 result.checks={dsa:{},system:{},stories:{},...result.checks};
 for(const key of ['dsa','system','stories'])if(!result.checks[key]||typeof result.checks[key]!=='object')throw Error('Invalid checklist');
 if(!Array.isArray(result.sessions))throw Error('Invalid sessions');
 result.weekly=result.weekly.map(t=>{if(!t||typeof t.id!=='string'||typeof t.text!=='string')throw Error('Invalid task');return {...t,done:!!t.done}});
 result.applications=result.applications.map(a=>{if(!a||typeof a.id!=='string'||typeof a.company!=='string'||typeof a.role!=='string')throw Error('Invalid application');return {...a,status:stages.includes(a.status)?a.status:'Applied',link:safeLink(a.link)}});
 result.sessions=result.sessions.map(s=>{if(!s||typeof s.id!=='string'||!validDate(s.date)||!Number.isFinite(s.minutes)||s.minutes<=0||s.minutes>1440||typeof s.track!=='string'||typeof s.note!=='string')throw Error('Invalid study session');return s});
 result.cert=Math.min(100,Math.max(0,Number(result.cert)||0));result.notes=typeof result.notes==='string'?result.notes:'';
 for(const [key,value] of Object.entries(result.reviews))if(!value||typeof value!=='object'||['wins','gaps','next'].some(k=>typeof value[k]!=='string'))throw Error('Invalid review');
 return result;
}
function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(dayDate(s))&&localDay(dayDate(s))===s}
function safeLink(s){try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
state=normalize({...baseState(),...state});
function rollover(){const key=monday(localDay());if(state.weekKey!==key){state.weekHistory[state.weekKey]=state.weekly.map(t=>({...t}));state.weekly=state.weekly.map(t=>({...t,done:false}));state.weekKey=key;}}
rollover();
let calendarMonth=localDay().slice(0,7),selectedDay=localDay();
const extra=document.createElement('section');extra.id='execution';extra.className='section';extra.innerHTML=`
<div class="section-head"><div><p class="eyebrow">CAREER OS / V2</p><h2>Turn intention into evidence.</h2></div><p class="section-note">Log focused work. Apply every week. Review what changes.</p></div>
<div class="metric-grid v2metrics"><article class="metric card"><span>Current streak</span><strong id="streak"></strong><small>Days with logged study</small></article><article class="metric card"><span>Study this week</span><strong id="studyHours"></strong><small id="studyTarget"></small></article><article class="metric card"><span>Active applications</span><strong id="activeApps"></strong><small>Applied through onsite</small></article><article class="metric card"><span>Certification</span><strong id="examCountdown"></strong><small id="examCaption"></small></article></div>
<div class="v2split"><article class="card v2panel"><div class="card-title"><button class="ghost small" id="prevMonth" aria-label="Previous month">←</button><h3 id="monthTitle"></h3><button class="ghost small" id="nextMonth" aria-label="Next month">→</button></div><div class="calendar-head">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<span>${x}</span>`).join('')}</div><div id="calendar" class="calendar"></div><p class="muted">Select a day to log or inspect study. Filled days have logged work.</p><div id="daySessions"></div></article>
<article class="card v2panel"><h3>Log a focused session</h3><form id="sessionForm" class="v2form"><label>Date<input type="date" id="sessionDate" required value="${selectedDay}" max="${localDay()}"></label><label>Track<select id="sessionTrack">${['DSA','Mobile system design','Android / Compose','React Native','Cloud / AWS','AI engineering','Staff leadership','Applications'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Minutes<input type="number" id="sessionMinutes" min="1" max="1440" required value="60"></label><label>Evidence / learning<textarea id="sessionNote" rows="3" maxlength="2000" placeholder="Problem solved, design explored, or lesson learned"></textarea></label><button class="primary" type="submit">Save study session</button></form><div id="allocation"></div></article></div>
<article class="card v2panel target-panel"><h3>Your next role</h3><form id="targetsForm" class="targets-form"><label>Target role<input id="targetRole" maxlength="120"></label><label>Annual salary target<input id="targetSalary" type="number" min="0" step="1000" placeholder="Optional"></label><label>Currency<select id="targetCurrency"><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option><option>AED</option></select></label><label>Location / remote<input id="targetLocation" maxlength="120" placeholder="Bengaluru / remote"></label><label>Weekly study hours<input id="targetHours" type="number" min="1" max="168" required></label><label>AWS exam date<input id="targetExam" type="date"></label><button class="primary small" type="submit">Save targets</button></form><p id="targetFeedback" role="status" class="muted"></p></article>`;
document.querySelector('#today').before(extra);
document.querySelector('.topnav').insertAdjacentHTML('afterbegin','<a href="#execution">Daily log</a>');
document.querySelector('#applications .table-wrap').insertAdjacentHTML('beforebegin','<div id="kanban" class="kanban" aria-label="Application stages"></div>');
const review=document.createElement('section');review.className='section';review.id='reviews';review.innerHTML=`<div class="section-head"><div><p class="eyebrow">REFLECT / ADJUST</p><h2>Make the next cycle better.</h2></div></div><article class="card v2panel"><div class="review-controls"><label>Review cycle<select id="reviewType"><option value="week">Weekly</option><option value="month">Monthly</option></select></label><label>Any date in the period<input type="date" id="reviewDate" value="${localDay()}" required></label></div><p id="reviewSummary" class="muted"></p><form id="reviewForm" class="v2form"><label>Wins and evidence<textarea id="reviewWins" rows="3" maxlength="5000"></textarea></label><label>Gaps and interview feedback<textarea id="reviewGaps" rows="3" maxlength="5000"></textarea></label><label>Next cycle commitments<textarea id="reviewNext" rows="3" maxlength="5000"></textarea></label><button class="primary" type="submit">Save review</button><p id="reviewFeedback" role="status" class="muted"></p></form></article>`;document.querySelector('#notes').before(review);
function sessionsFor(start,end){return state.sessions.filter(s=>s.date>=start&&s.date<=end)}
function hours(list){return (list.reduce((n,s)=>n+s.minutes,0)/60).toFixed(1)}
function renderExecution(){
 const today=localDay(),week=monday(today);document.querySelector('#studyHours').textContent=`${hours(sessionsFor(week,today))} h`;document.querySelector('#studyTarget').textContent=`Goal: ${state.targets.hours} hours / week`;
 const days=new Set(state.sessions.map(s=>s.date));let cursor=days.has(today)?today:shiftDay(today,-1),streak=0;while(days.has(cursor)){streak++;cursor=shiftDay(cursor,-1)}document.querySelector('#streak').textContent=`${streak} days`;
 document.querySelector('#activeApps').textContent=state.applications.filter(a=>!['Offer','Closed'].includes(a.status)).length;
 const exam=state.targets.exam;const remaining=validDate(exam)?Math.round((Date.UTC(...exam.split('-').map((v,i)=>i===1?Number(v)-1:Number(v)))-Date.UTC(...today.split('-').map((v,i)=>i===1?Number(v)-1:Number(v))))/86400000):null;
 document.querySelector('#examCountdown').textContent=remaining===null?'Set a date':remaining<0?'Date passed':remaining===0?'Today':`${remaining} days`;
 document.querySelector('#examCaption').textContent=exam||'Choose your AWS exam target below';
 const first=`${calendarMonth}-01`,offset=(dayDate(first).getDay()+6)%7;const date=dayDate(first);document.querySelector('#monthTitle').textContent=date.toLocaleDateString('en-IN',{month:'long',year:'numeric'});date.setMonth(date.getMonth()+1);date.setDate(0);const count=date.getDate();
 document.querySelector('#calendar').innerHTML='<span></span>'.repeat(offset)+Array.from({length:count},(_,i)=>{const day=`${calendarMonth}-${String(i+1).padStart(2,'0')}`,minutes=sessionsFor(day,day).reduce((n,s)=>n+s.minutes,0);return `<button class="calendar-day ${minutes?'studied':''} ${day===selectedDay?'selected':''}" data-day="${day}" aria-label="${day}, ${minutes} minutes" aria-pressed="${day===selectedDay}">${i+1}<small>${minutes?`${minutes}m`:'·'}</small></button>`}).join('');
 document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{selectedDay=b.dataset.day;document.querySelector('#sessionDate').value=selectedDay;renderExecution()});
 document.querySelector('#daySessions').innerHTML=`<p class="label">${selectedDay}</p>`+sessionsFor(selectedDay,selectedDay).map(s=>`<div class="session-row"><div><strong>${esc(s.track)} · ${s.minutes}m</strong><p>${esc(s.note)}</p></div><button class="ghost small" data-remove-session="${esc(s.id)}" aria-label="Delete study session">×</button></div>`).join('')+(sessionsFor(selectedDay,selectedDay).length?'':'<p class="muted">No sessions logged.</p>');
 document.querySelectorAll('[data-remove-session]').forEach(b=>b.onclick=()=>{state.sessions=state.sessions.filter(s=>s.id!==b.dataset.removeSession);save();renderExecution();renderReview()});
 document.querySelector('#allocation').innerHTML='<p class="label">THIS WEEK / ACTUAL HOURS</p>'+[...new Set(state.sessions.map(s=>s.track))].map(t=>`<div class="score-row"><span>${esc(t)}</span><strong>${hours(sessionsFor(week,today).filter(s=>s.track===t))} h</strong></div>`).join('');
}
const originalRenderApplications=renderApplications;
renderApplications=()=>{originalRenderApplications();document.querySelector('#kanban').innerHTML=stages.map(stage=>`<article class="kanban-column"><h3>${stage} <small>${state.applications.filter(a=>a.status===stage).length}</small></h3>${state.applications.filter(a=>a.status===stage).map(a=>`<div class="kanban-card"><strong>${esc(a.company)}</strong><p>${esc(a.role)}</p><small>${esc(a.date||'')}</small><label>Move to<select data-move="${esc(a.id)}">${stages.map(s=>`<option ${s===stage?'selected':''}>${s}</option>`).join('')}</select></label></div>`).join('')||'<p class="muted">No applications</p>'}</article>`).join('');document.querySelectorAll('[data-move]').forEach(s=>s.onchange=()=>{state.applications.find(a=>a.id===s.dataset.move).status=s.value;save();renderApplications();renderExecution()});renderExecution();};
function reviewPeriod(){const d=document.querySelector('#reviewDate').value||localDay(),type=document.querySelector('#reviewType').value;if(type==='week'){const start=monday(d);return {key:`week:${start}`,start,end:shiftDay(start,6)}}const start=d.slice(0,7)+'-01',endDate=dayDate(start);endDate.setMonth(endDate.getMonth()+1);endDate.setDate(0);return {key:`month:${start.slice(0,7)}`,start,end:localDay(endDate)}}
function renderReview(){const p=reviewPeriod(),r=state.reviews[p.key]||{};for(const [field,id]of [['wins','Wins'],['gaps','Gaps'],['next','Next']])document.querySelector(`#review${id}`).value=r[field]||'';document.querySelector('#reviewFeedback').textContent='';document.querySelector('#reviewSummary').textContent=`${p.start} → ${p.end} · ${hours(sessionsFor(p.start,p.end))} study hours · ${sessionsFor(p.start,p.end).length} sessions · ${state.applications.filter(a=>a.createdDay&&a.createdDay>=p.start&&a.createdDay<=p.end).length} dated applications. Older V1 applications are retained but excluded from period counts.`}
init();
for(const [key,id]of Object.entries({role:'Role',salary:'Salary',currency:'Currency',location:'Location',hours:'Hours',exam:'Exam'}))document.querySelector(`#target${id}`).value=state.targets[key];
document.querySelector('#targetsForm').onsubmit=e=>{e.preventDefault();for(const [key,id]of Object.entries({role:'Role',salary:'Salary',currency:'Currency',location:'Location',hours:'Hours',exam:'Exam'}))state.targets[key]=document.querySelector(`#target${id}`).value;state.targets.hours=Number(state.targets.hours);save();renderExecution();document.querySelector('#targetFeedback').textContent='Targets saved.'};
document.querySelector('#sessionForm').onsubmit=e=>{e.preventDefault();const date=document.querySelector('#sessionDate').value;if(date>localDay())return;state.sessions.push({id:crypto.randomUUID(),date,track:document.querySelector('#sessionTrack').value,minutes:Number(document.querySelector('#sessionMinutes').value),note:document.querySelector('#sessionNote').value.trim()});selectedDay=date;calendarMonth=date.slice(0,7);save();renderExecution();renderReview();document.querySelector('#sessionNote').value=''};
for(const [id,delta] of [['prevMonth',-1],['nextMonth',1]])document.querySelector(`#${id}`).onclick=()=>{const d=dayDate(calendarMonth+'-01');d.setMonth(d.getMonth()+delta);calendarMonth=localDay(d).slice(0,7);renderExecution()};
document.querySelector('#reviewForm').onsubmit=e=>{e.preventDefault();state.reviews[reviewPeriod().key]={wins:document.querySelector('#reviewWins').value,gaps:document.querySelector('#reviewGaps').value,next:document.querySelector('#reviewNext').value};save();document.querySelector('#reviewFeedback').textContent='Review saved.'};
for(const id of ['reviewType','reviewDate'])document.querySelector(`#${id}`).onchange=renderReview;
// Replace V1 import handler with validated import; never mutate state before validation succeeds.
const oldImport=document.querySelector('#importInput'),newImport=oldImport.cloneNode();oldImport.replaceWith(newImport);newImport.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const candidate=normalize(JSON.parse(await f.text()));localStorage.setItem(STORAGE_KEY,JSON.stringify(candidate));location.reload()}catch{alert('Invalid Career OS backup. Your current progress has not changed.')}finally{e.target.value=''}};
document.querySelector('#applicationForm').addEventListener('submit',()=>{if(state.applications[0]){state.applications[0].createdDay=localDay();state.applications[0].link=safeLink(state.applications[0].link);save();renderApplications();renderReview()}});
// Keep week boundaries correct when the dashboard stays open overnight.
function refreshDay(){rollover();save();renderWeekly();renderExecution();renderReview();document.querySelector('#sessionDate').max=localDay()}
window.addEventListener('focus',refreshDay);renderExecution();renderReview();save();
