const architectureDiagrams=[
 {id:'offline',title:'Offline-first mobile platform',track:'architecture',note:'The UI reads local truth. Network synchronization updates the local store, including pending writes and conflicts.',rows:[['User action / screen'],['ViewModel / presentation state'],['Domain operation'],['Repository boundary'],['Local database / cache','Persistent outbox'],['Render local state','Sync worker → authorized API'],['Observe local changes','Resolve versions / conflicts']],edges:[[0,1],[1,2],[2,3],[3,4,'read'],[3,5,'write'],[4,6],[5,7],[6,8],[7,9]],steps:['Read cached records even without connectivity.','Write the local change and durable operation ID together where possible.','Retry the outbox under the server idempotency contract.','Reconcile remote results into local storage; show unresolved failures.']},
 {id:'ios',title:'iOS: state, domain, and data',track:'ios',note:'A suggested responsibility split. Concrete actor isolation and persistence contexts must be defined by the implementation.',rows:[['SwiftUI / UIKit screen'],['Owned state model / MainActor'],['Use case / domain rule'],['Repository protocol'],['Core Data / SwiftData','URLSession / API'],['Local snapshot','Validated remote model']],edges:[[0,1,'events'],[1,2],[2,3],[3,4],[3,5],[4,6],[5,7]],steps:['The screen sends events; it does not own every service.','The model derives UI state and owns cancellation.','Repositories expose stable contracts and map remote data.','Publish approved results through the appropriate isolation boundary.']},
 {id:'android',title:'Android: unidirectional state flow',track:'android',note:'UI state flows down, actions flow up. Persisted records can survive a process ending; the ViewModel itself cannot.',rows:[['Compose screen'],['ViewModel: UI state + actions'],['Use case (when useful)'],['Repository'],['Room / local records','Remote data source'],['Flow → lifecycle collection','Sync / constrained worker']],edges:[[0,1,'action'],[1,2],[2,3],[3,4],[3,5],[4,6,'state'],[5,7]],steps:['Compose reads state and emits intent events.','The ViewModel exposes observable screen state.','Room can be the read source while remote results update it.','Collect UI flows with lifecycle awareness and restore minimal saved state.']},
 {id:'rn',title:'React Native: Fabric rendering flow',track:'rn',note:'These are logical stages, not a fixed three-thread guarantee. Native modules have their own execution contracts.',rows:[['React props / state update'],['Render: new shadow tree'],['Commit: prepare + layout'],['Mount: native host updates'],['iOS host views','Android host views'],['Visible frame / input']],edges:[[0,1],[1,2],[2,3],[3,4],[3,5],[4,6],[5,6]],steps:['React work produces an immutable renderer shadow tree.','Commit performs preparation including layout.','Mount applies host-view updates on the platform UI path.','JSI interop does not automatically make every native operation cheap or thread-safe.']},
 {id:'auth',title:'Token refresh without a request storm',track:'architecture',note:'Share one refresh operation and bound retries. A rejected refresh ends the authenticated session; it does not loop forever.',rows:[['API request → expired response'],['Join single-flight refresh'],['Refresh succeeds?'],['Yes: persist new credentials','No: clear session / sign-in'],['Retry original request once','Preserve safe user input']],edges:[[0,1],[1,2],[2,3,'yes'],[2,4,'no'],[3,5],[4,6]],decision:2,steps:['Concurrent failed calls wait on one refresh owner.','Validate and store fresh credentials securely.','Retry under a bounded policy and protect mutation idempotency.','If revoked, transition to sign-in and communicate the recovery path.']},
 {id:'cloud',title:'Mobile → cloud architecture',track:'cloud',note:'Gateway access checks and service resource authorization are separate. Storage and queue operations need explicit consistency rules.',rows:[['iOS / Android / RN client'],['API gateway / identity validation'],['Authorized application service'],['Database / cache','Queue / event'],['Versioned API result','Idempotent worker'],['Client reconciliation','Side effect / durable result']],edges:[[0,1],[1,2],[2,3],[2,4],[3,5],[4,6],[5,7],[6,8]],steps:['Validate identity at the trusted backend boundary.','Enforce resource permissions and domain rules in the service.','Persist state and events under a deliberate transactional strategy.','Workers tolerate duplicate delivery and expose outcomes for reconciliation.']},
 {id:'rag',title:'Grounded AI / RAG feature',track:'ai',note:'Retrieval and generation are distinct failure points. Model output and tool arguments remain untrusted until validated.',rows:[['User question + trusted identity'],['Authorize corpus + retrieve'],['Relevant evidence + task context'],['Model generates candidate'],['Validate output / citations'],['Answer with evidence','Abstain / ask for missing data']],edges:[[0,1],[1,2],[2,3],[3,4],[4,5,'valid'],[4,6,'unsupported']],decision:4,steps:['Permission-filter candidate documents before exposing them.','Check retrieval evidence separately from fluent generation.','Validate structured content and consequential tool actions.','Measure task quality, latency, cost, and failure behavior.']},
 {id:'release',title:'Safe mobile release and rollback',track:'staff',note:'A kill switch can disable eligible behavior but cannot instantly replace every installed native binary.',rows:[['Versioned source + dependencies'],['Tests / native build / contracts'],['Release artifact + symbols'],['Small rollout cohort'],['Guardrail metrics healthy?'],['Expand rollout','Pause / flag off / recover']],edges:[[0,1],[1,2],[2,3],[3,4],[4,5,'yes'],[4,6,'no']],decision:4,steps:['Keep artifacts, maps, and symbols tied to exact builds.','Exercise critical delivered-device journeys.','Watch crashes, latency, and meaningful transaction outcomes.','Rollback traffic or flags with compatible backend and data behavior.']}
];
function diagramSVG(data){let id=0;const nodes=[];data.rows.forEach((row,r)=>row.forEach((text,c)=>nodes.push({id:id++,text,x:row.length===1?340:180+c*320,y:55+r*95})));const marker=`arrow-${data.id}`,height=data.rows.length*95+10;return `<svg viewBox="0 0 680 ${height}" role="img" aria-label="${esc(data.title)}"><title>${esc(data.title)}</title><desc>${esc(data.note)}</desc><defs><marker id="${marker}" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8 Z" fill="var(--accent2)"/></marker></defs>${data.edges.map(([from,to,label])=>{const a=nodes[from],b=nodes[to];return `<path d="M${a.x} ${a.y+24} L${a.x} ${a.y+47} L${b.x} ${b.y-47} L${b.x} ${b.y-24}" fill="none" stroke="var(--accent2)" stroke-width="2" marker-end="url(#${marker})"/>${label?`<text x="${(a.x+b.x)/2+7}" y="${(a.y+b.y)/2}" fill="var(--muted)" font-size="12">${esc(label)}</text>`:''}`}).join('')}${nodes.map(n=>`<rect x="${n.x-140}" y="${n.y-24}" width="280" height="48" rx="${data.decision===n.id?22:10}" fill="var(--panel2)" stroke="${data.decision===n.id?'var(--accent)':'var(--line)'}" stroke-width="2"/><text x="${n.x}" y="${n.y+5}" text-anchor="middle" fill="var(--text)" font-size="14">${esc(n.text)}</text>`).join('')}</svg>`}
// 50 guides align with the DSA library; additional sorting guides follow.
const algorithmRows=`
Complexity analysis|Compare algorithms before coding|Depends on algorithm|Define input size;Count dominant operations;Separate worst and expected cases;Count auxiliary and output space;Check edge cases and language costs|A scan is O(n); a nested full scan is O(n²).|work = number of operations as n grows
Hash-map tradeoffs|Fast lookup with extra memory|Expected O(1) per operation|Define keys and equality;Insert known values;Look up needed keys;Handle duplicates and ordering;State collision and space assumptions|For [2,7,11] and target 9, look for each value's complement.|lookup by key; maintain counts or indices
Sliding-window pattern|Contiguous ranges with a valid invariant|Often O(n), if pointers only advance|Define the window invariant;Start an empty window;Expand right;Shrink while the constraint requires;Record the best valid result|For abcabcbb, the longest distinct window has length 3.|for right: add item; while invalid: remove left; update best
Binary search|Sorted values or a monotone predicate|O(log n), O(1) iterative space|Choose a bound convention;Set low and high;Inspect midpoint;Discard the impossible half;Return match or boundary|Searching 7 in [1,3,5,7,9] checks 5, then 7.|while low <= high: mid=low+(high-low)/2; move a bound
BFS versus DFS|Graph or tree exploration|O(V+E) with adjacency lists|Choose frontier type;Mark the initial node;Take the next frontier node;Add eligible unvisited neighbors;Stop at goal or exhaust frontier|Unweighted A→B→D is 2 edges; BFS discovers layers.|BFS uses queue; DFS uses stack or recursion
Heaps and intervals|Selection and overlap problems|Usually O(n log k) or O(n log n)|Clarify the required result;Choose heap or interval ordering;Process items under the invariant;Update selected items or merged range;Return result with tie policy|Top 2 of [9,2,7] are 9 and 7; [1,3] and [2,4] merge.|heap for bounded selection; sorted scan for intervals
Dynamic-programming pattern|Overlapping subproblems with reusable states|Depends on states × transitions|Define the state;Define base cases;Derive transitions;Evaluate in dependency order;Read the answer and consider space reuse|Fibonacci: dp[0]=0, dp[1]=1; dp[5]=5.|dp[state] = combination of already-solved states
Interview problem flow|An unfamiliar coding problem|Analyze the chosen algorithm|Clarify constraints;Show a correct baseline;State an improved invariant;Implement and test boundaries;Explain time and space|Before Two Sum, ask whether indices or values are required.|clarify → derive → implement → test → analyze
Two Sum|Pair indices adding to a target|Expected O(n), O(n) space|Create a value-to-index map;Scan the next value;Look for target minus value;Return distinct indices if found;Otherwise store value and continue|[2,7,11,15], target 9 → indices [0,1].|for i,x: if target-x in seen return [seen[target-x],i]; seen[x]=i
Contains duplicate|Detect repeated array values|Expected O(n), O(n) space|Create an empty set;Read the next value;Check whether already seen;Return true on repetition;Otherwise insert and continue|[1,2,1] → true; [1,2,3] → false.|for x: if x in seen return true; add x; return false
Valid anagram|Compare character multisets|O(n), alphabet-dependent space|Agree on normalization;Check compatible lengths;Count first-string symbols;Subtract second-string symbols;Require balanced counts|listen and silent → anagrams.|counts[symbol] += 1; counts[other] -= 1; require all zero
Sorted pair sum|Find a pair in sorted input|O(n), O(1) space|Put pointers at both ends;Compute the current sum;Return if equal to target;Move left for a small sum or right for a large sum;Stop when pointers meet|[1,2,4,7], target 9 → 2+7.|while l<r: sum=a[l]+a[r]; compare and move one pointer
Sorted deduplication|Keep a unique prefix in place|O(n), O(1) space|Handle empty input;Set write after first item;Scan remaining values;Write when different from previous unique;Return the prefix length|[1,1,2,2,3] → prefix [1,2,3], length 3.|for read: if a[read] != a[write-1]: a[write++]=a[read]
Move zeroes|Stable in-place nonzero compaction|O(n), O(1) space|Set write to zero;Scan all values;Write every nonzero in order;Fill the remaining suffix with zero;Return the mutated array|[0,1,0,3,12] → [1,3,12,0,0].|for x: if x!=0 a[write++]=x; fill suffix with 0
Kadane maximum subarray|Maximum contiguous sum|O(n), O(1) space|Initialize from the first item;Read the next value;Choose restart or extend;Update global best;Continue through all items|[-2,1,-3,4,-1,2,1,-5,4] → sum 6 from [4,-1,2,1].|ending=max(x,ending+x); best=max(best,ending)
Product except self|Products without division|O(n), O(1) auxiliary excluding output|Initialize output to ones;Write prefix products;Start suffix at one;Multiply outputs by suffix in reverse;Return products and check overflow|[1,2,3,4] → [24,12,8,6].|out[i]=prefix; prefix*=a[i]; reverse: out[i]*=suffix; suffix*=a[i]
Merge sorted arrays|Merge into available trailing capacity|O(m+n), O(1) auxiliary|Set pointers at valid tails;Set output pointer at final capacity;Choose the larger tail value;Write backward and move that pointer;Copy any remaining second-array prefix|[1,3,0,0] with valid length 2 plus [2,4] → [1,2,3,4].|while j>=0: a[k--]= i>=0 && a[i]>b[j] ? a[i--] : b[j--]
Normalized palindrome|Check symmetric allowed symbols|O(n), normalization-dependent space|Define text rules;Put pointers at ends;Skip excluded symbols;Compare normalized pairs;Advance or reject mismatch|A man, a plan, a canal: Panama → true under alphanumeric rules.|while l<r: skip excluded; compare; l++; r--
Longest distinct substring|Longest substring without repeated symbols|Expected O(n), O(distinct symbols) space|Create last-seen map;Read the next symbol;Advance left beyond an in-window duplicate;Update last position;Update maximum window length|abba → length 2, not 3; left must never move backward.|left=max(left,last[x]+1); last[x]=right; best=max(best,right-left+1)
Minimum covering window|Shortest substring containing required multiplicities|Expected O(n+m), O(alphabet) space|Count required symbols;Expand and update missing counts;When covered, record candidate;Shrink while still covered;Return shortest candidate|ADOBECODEBANC with ABC → BANC.|expand right; while covered: update best; remove left
Negative-sum caveat|Check whether a sum window is valid|Algorithm-dependent|State the assumed monotonicity;Try a negative-value example;Notice expansion or shrink can reverse direction;Choose a correct prefix or ordered technique;Prove the new invariant|[2,-1,2] shows expanding can reduce a sum before increasing it.|do not use positive-only window logic for arbitrary negative values
Prefix-sum ranges|Many static range-sum queries|O(n) build, O(1) query, O(n) space|Create prefix[0]=0;Accumulate values;Translate inclusive query bounds;Subtract the two prefixes;Rebuild or change technique for updates|[2,4,1] → prefixes [0,2,6,7]; sum indices 1..2 = 7-2 = 5.|prefix[i+1]=prefix[i]+a[i]; sum(l,r)=prefix[r+1]-prefix[l]
Count target-sum subarrays|Count contiguous sums including negatives|Expected O(n), O(n) space|Seed frequency of zero to one;Advance prefix sum;Count earlier prefix minus target;Add that count to result;Insert current prefix after lookup|[1,1,1], target 2 → 2 subarrays.|count+=freq[prefix-target]; freq[prefix]++
Valid parentheses|Validate nested bracket types|O(n), O(n) space|Create stack;Push opening brackets;For a closing bracket require a matching top;Pop the matching opener;Require an empty final stack|([]) → valid; ([)] → invalid.|if open push; else require matching pop; return stack empty
Min stack|Minimum with stack operations|O(1) operation, O(n) space|Initialize value and minimum storage;Push value with minimum-so-far;Pop matching stored state;Read minimum from the top;Define empty-stack behavior|Push 3,1,2 → min 1; pop 2 and 1 → min 3.|push(x,min(x,currentMin)); pop(); min=top.minimum
Next greater element|Resolve values awaiting a greater item|O(n), O(n) space|Create unresolved index stack;Scan each value;While current resolves stack top, record answer;Push current index;Mark remaining entries as not found|[2,1,3] → [3,3,none].|while stack && a[i]>a[top]: answer[pop]=a[i]; push i
Queue with two stacks|FIFO using LIFO primitives|Amortized O(1), O(n) space|Push new items to input stack;On dequeue check output stack;If empty, transfer all input items;Pop from output;Define empty behavior|Enqueue A,B; transfer yields output top A, so A leaves first.|enqueue: in.push; dequeue: if out empty transfer; out.pop
Reverse linked list|Reverse links without extra nodes|O(n), O(1) space|Set previous to null;Read current next before mutation;Point current to previous;Advance previous and current;Return previous as new head|1→2→3 becomes 3→2→1.|next=cur.next; cur.next=prev; prev=cur; cur=next
Cycle detection|Detect cycle and optionally its entry|O(n), O(1) space|Start slow and fast at head;Advance by one and two;Stop if fast reaches null;On meeting reset one pointer to head;Advance equally to locate cycle entry|1→2→3→2 has a cycle entering node 2.|slow=slow.next; fast=fast.next.next; after meeting walk equally
Merge sorted lists|Reuse nodes in a sorted chain|O(m+n), O(1) auxiliary|Create dummy result head;Compare current heads;Attach smaller node and advance it;Advance result tail;Attach remaining suffix|1→3 plus 2→4 → 1→2→3→4.|while both: attach smaller; tail.next=remaining; return dummy.next
Remove nth from end|Remove without first measuring length|O(n), O(1) space|Create dummy before head;Advance lead pointer to form gap;Move both until lead reaches end;Relink around the target;Return dummy next and validate n|1→2→3→4, n=2 → 1→2→4.|use dummy; advance fast n; move until fast.next null; skip slow.next
Tree traversals|Visit nodes in deliberate order|O(n), O(height) recursive space|Choose before-between-after processing;Visit child branches;Process node at selected time;Accumulate output if required;Account for skewed depth|For root 2 with children 1,3: inorder [1,2,3], preorder [2,1,3].|pre=node,left,right; in=left,node,right; post=left,right,node
Maximum tree depth|Longest root-to-leaf node count|O(n), O(height) recursion|Empty tree returns zero;Compute left depth;Compute right depth;Take the larger child result;Return one plus that result|Root plus one child has depth 2.|depth(node)=node ? 1+max(depth(left),depth(right)) : 0
Validate BST|Check all ancestor ordering bounds|O(n), O(height) space|Begin with unbounded interval;Check node against interval;Pass upper bound to left child;Pass lower bound to right child;Reject any descendant violation|Root 10, left child 5 with right child 12 → invalid despite local 5<12.|valid(node,lo,hi)=lo<value<hi and valid children with narrowed bounds
Lowest common ancestor|Find shared ancestry in a general tree|O(n), O(height) space|Handle null or target node;Search left subtree;Search right subtree;If both find targets return current;Otherwise return the found branch|Targets in root's two different subtrees have root as LCA.|left=find(left); right=find(right); return node if both found; otherwise return the found branch
Tree serialization|Save enough information to rebuild shape|O(n), O(n) output|Choose traversal and null markers;Write node or null token;Recurse through ordered children;Parse using the same grammar;Verify round-trip and malformed input|Root 1 with left 2 → preorder 1,2,#,#,#.|encode node,left,right with null markers; decode consumes tokens recursively
Graph representations|Choose storage for graph density and queries|Lists O(V+E), matrix O(V²) space|Count vertices and edges;Identify traversal or edge-check needs;Compare list and matrix storage;Build chosen representation;State directed and duplicate-edge rules|A sparse 1000-node graph need not allocate a million matrix cells.|list[u].append(v); matrix[u][v]=true for the respective representation
Topological sort|Order prerequisites in a DAG|O(V+E), O(V+E) storage|Compute indegrees;Queue all zero-indegree nodes;Remove a ready node;Decrement outgoing neighbors and enqueue newly ready;Require result count equals vertex count|A→C and B→C permits A,B,C or B,A,C.|while queue: pop; emit; decrement neighbors; reject if emitted<V
Dijkstra shortest path|Shortest paths with nonnegative weights|Typical O((V+E) log V) heap approach|Set source distance zero;Push source into min-priority queue;Pop a nonstale best candidate;Relax neighbors and push improvements;Stop when queue exhausted or goal settled|A→B cost 2, B→C 1, A→C 5 → C distance 3.|if dist[u]+w<dist[v]: update and push; skip stale heap entries
Union-find|Track components under merging|Near-constant amortized with heuristics|Initialize each item as its parent;Find representatives with compression;Compare representatives;Union by size or rank if distinct;Query membership through representatives|Union A,B then B,C → A and C share a representative.|find compresses parent path; union attaches smaller rank or size
Count islands|Count connected land components|O(rows×cols), O(rows×cols) worst space|Define neighbor rule;Scan each cell;For unvisited land count one component;Flood-fill that component;Continue to next unvisited land|With 4-neighbors, diagonal land cells are separate islands.|for each cell: if unvisited land: count++; BFS or DFS mark component
Backtracking|Explore constrained choices with undo|Often exponential; include output size|Define current path and choices;Check terminal condition;Choose an eligible option;Recurse and prune impossible paths;Undo choice before next branch|Subsets of [1,2] → [],[1],[2],[1,2].|choose; recurse; undo; record when terminal
Coin change minimum|Unlimited positive denominations|O(amount×coins), O(amount) space|Set dp[0]=0 and others unreachable;Visit amounts in ascending order;Try each usable coin;Update from reachable smaller amount;Return value or impossible|Coins [1,3,4], amount 6 → 2 coins (3+3), not greedy 4+1+1.|dp[a]=min(dp[a],dp[a-coin]+1) for reachable states
House robber|Maximum sum with no adjacent choices|O(n), O(1) working space|Define whether empty choice is allowed;Initialize prior states;Compare skip with take plus two-back;Advance rolling values;Return final best|[2,7,9,3,1] → 12 using 2+9+1.|best=max(prev1,prev2+x); prev2=prev1; prev1=best
Longest increasing subsequence|Longest strictly increasing noncontiguous sequence|O(n log n), O(n) space|Start empty minimum tails;For each value find first tail not smaller;Replace that tail or append;Continue through values;Tail count is LIS length|[10,9,2,5,3,7,101,18] → length 4.|i=lower_bound(tails,x); replace or append x
Merge intervals|Combine overlapping ranges|O(n log n), O(n) output|Sort intervals by start;Start the current merged range;Extend while overlap holds;Emit completed ranges;Apply agreed endpoint semantics|[1,3],[2,6],[8,10] → [1,6],[8,10].|if next.start<=cur.end: cur.end=max ends; else emit and replace
Meeting rooms|Peak simultaneous resource demand|O(n log n), O(n) space|Sort starts or events;Track active end times;Remove meetings finished before next start;Allocate next meeting;Track peak active count|[0,30],[5,10],[15,20] → 2 rooms.|pop ends <= start; push end; best=max(best,heap size)
Top-k frequent|Select by frequency not numeric magnitude|Heap O(n+u log k), O(u+k) space|Count unique-value frequencies;Maintain bounded min-heap;Keep better candidates under tie rules;Extract chosen values;Validate k limits|[1,1,1,2,2,3], k=2 → [1,2].|count values; push frequency candidates; remove weakest when heap>k
LRU cache|Bounded recency eviction|Expected O(1) operation, O(capacity) space|Use key-to-node map and linked list;On hit move node to recent end;On update move or insert;On overflow remove least recent;Handle zero capacity and concurrency|Capacity 2: put A,B; get A; put C → evict B.|get: lookup+move; put: insert/update+move+evict
Text and indexing|Respect language-specific text cost|Depends on encoding and operations|Define bytes or character semantics;Choose appropriate iteration;Avoid assumed constant-time indices;Normalize only under the contract;Reevaluate time and memory bounds|An emoji may contain multiple code units or scalars; byte length differs.|iterate using the language's appropriate text units
Bubble sort|Understand local adjacent swaps|O(n²) worst, O(1) space|Start an unsorted pass;Compare adjacent values;Swap if out of order;Reduce unsorted suffix;Stop early if no swaps|[3,1,2] → [1,3,2] → [1,2,3].|repeat passes; swap neighbors; stop if unchanged
Insertion sort|Small or nearly sorted data|O(n²) worst, O(1) space|Treat first item as sorted;Take the next key;Shift larger prefix items right;Insert key into the gap;Repeat through input|[3,1,2] inserts 1 before 3, then 2 between them.|for i: key=a[i]; shift larger left-prefix values; insert
Selection sort|Illustrate minimum selection|O(n²), O(1) space|Start next output position;Find minimum of remaining suffix;Swap it into position;Advance output boundary;Repeat until sorted|[3,1,2] → [1,3,2] → [1,2,3].|for i: find suffix min; swap(a[i],a[min])
Merge sort|Stable divide-and-conquer sorting with suitable merge|O(n log n), O(n) typical array space|Split a range;Recursively sort left;Recursively sort right;Merge ordered ranges;Return the combined sorted range|[4,1,3,2] → [1,4] and [2,3] → [1,2,3,4].|sort halves; merge with left-first choice on equal values for stability
Quicksort|In-place partitioning with pivot strategy|Average O(n log n), worst O(n²)|Choose a pivot;Partition by the defined rule;Place or separate pivot region;Sort remaining partitions;Bound stack depth and adverse cases|[3,1,4,2] around pivot 2 separates smaller 1 from larger 3,4.|partition; recursively sort nonpivot partitions
Heap sort|Worst-case n log n in-place array sorting|O(n log n), O(1) iterative auxiliary|Build a max heap;Swap root with final active item;Shrink active heap;Sift root down;Repeat until active size is one|[3,1,2] → max heap; place 3, then 2, then 1.|heapify; for end descending: swap root/end; sift within active heap
`;
const dsaVisuals=algorithmRows.trim().split('\n').map((row,index)=>{const [title,when,complexity,steps,example,pseudo]=row.split('|');return {id:`algo-${index}`,title,when,complexity,steps:steps.split(';'),example,pseudo}});
const releaseSnapshot={checked:'2026-10-04',platforms:[
 {key:'ios',name:'iOS',version:'27.0.1',status:'Latest stable patch verified',date:'28 Sep 2026',preview:'27.2 beta 2 is a preview, not the stable release.',sources:[['Stable release list','https://support.apple.com/en-us/100100'],['What’s new in iOS 27','https://developer.apple.com/ios/whats-new/'],['Developer releases','https://developer.apple.com/news/releases/']],highlights:['Foundation Models gains broader model integration, multimodal prompts, and dynamic profiles.','SwiftUI adds document, reordering, and lazy-content capabilities; UIKit adds adaptive layouts.','App Intents and WidgetKit updates expand how app actions and widgets integrate with the system.'],practice:['Review availability checks and supported devices before adopting new APIs.','Build a small SwiftUI adaptation or Foundation Models example and test failure paths.','Compare SDK release notes with the app’s minimum supported OS.']},
 {key:'android',name:'Android',version:'17 · API 37',status:'Latest stable major platform verified',date:'16 Jun 2026',preview:'Android 17 QPR2 Beta 6 is a preview update. Pixel builds and OEM rollout dates vary.',sources:[['Stable Android 17 announcement','https://developer.android.com/blog/posts/android-17-is-here'],['Features and APIs','https://developer.android.com/about/versions/17/features'],['Target-SDK behavior changes','https://developer.android.com/about/versions/17/behavior-changes-17'],['QPR preview status','https://developer.android.com/about/versions/17/qpr2/release-notes']],highlights:['Targeting API 37 requires greater large-screen adaptability, with documented exemptions.','Runtime and profiling changes include memory safeguards, generational collection, and new profiling triggers.','New contacts-picker and protection capabilities extend privacy-oriented platform integrations.'],practice:['Check both all-app and target-SDK-specific behavior changes.','Exercise tablet/resizing, process restoration, memory, and background scenarios.','Review dependencies and permissions before changing targetSdk.']},
 {key:'rn',name:'React Native',version:'0.87.1',status:'Latest stable patch verified',date:'26 Aug 2026',preview:'0.88 is scheduled for 12 Oct 2026; a scheduled release is not yet stable.',sources:[['Official stable patch','https://github.com/react/react-native/releases/tag/v0.87.1'],['0.87 migration highlights','https://reactnative.dev/blog/2026/08/11/react-native-0.87'],['Release schedule','https://reactnative.dev/releases/overview']],highlights:['Strict TypeScript API becomes the default; migrate unsupported deep imports.','Metro 0.87 updates build tooling; Swift Package Manager support is experimental, with CocoaPods still supported.','Review newer Node/Kotlin/AGP requirements and removed APIs such as InteractionManager.'],practice:['Run the official upgrade diff and type checks before native builds.','Audit native modules, generated interfaces, and CI toolchains.','Measure delivered app behavior and stage rollout; keep experimental setup out of production until supported.']}
]};
const updates=document.createElement('section');updates.id='updates';updates.className='section';updates.innerHTML=`<div class="section-head"><div><p class="eyebrow">PLATFORM RADAR / CHECKED 04 OCT 2026</p><h2>Latest versions. What to learn next.</h2></div></div><p class="muted">A dated snapshot of official sources, not a live auto-updating feed. Stable versions and previews are shown separately; use the source links to check newer releases.</p><div class="release-grid">${releaseSnapshot.platforms.map(p=>`<article class="card v2panel release-card"><p class="label">${p.name}</p><h3>${p.version}</h3><small>${p.status} · ${p.date}</small><p class="muted">${esc(p.preview)}</p><h4>What’s new in this release family</h4><ul>${p.highlights.map(s=>`<li>${esc(s)}</li>`).join('')}</ul><h4>Practice checklist</h4><ul>${p.practice.map(s=>`<li>${esc(s)}</li>`).join('')}</ul><div class="release-links">${p.sources.map(([name,url])=>`<a href="${url}" class="table-link" target="_blank" rel="noreferrer">${esc(name)} ↗</a>`).join('')}</div><a class="secondary small" href="#learning/${p.key}">Open ${p.name} questions →</a></article>`).join('')}</div>`;
const visuals=document.createElement('section');visuals.className='section';visuals.id='visuals';visuals.innerHTML=`<div class="section-head"><div><p class="eyebrow">SEE THE SYSTEM / FOLLOW THE FLOW</p><h2>Architecture and algorithm guides.</h2></div><p class="section-note">8 architecture diagrams · ${dsaVisuals.length} DSA guides</p></div><div class="card v2panel"><label class="guide-label">Architecture<select id="architectureSelect">${architectureDiagrams.map(d=>`<option value="${d.id}">${esc(d.title)}</option>`).join('')}</select></label><div id="architectureGuide"></div></div><div class="card v2panel dsa-guide-panel"><div class="guide-controls"><label class="guide-label">Find an algorithm<input id="algorithmSearch" type="search" placeholder="Binary search, BFS, coin change…"></label><label class="guide-label">Algorithm / concept<select id="algorithmSelect">${dsaVisuals.map(d=>`<option value="${d.id}">${esc(d.title)}</option>`).join('')}</select></label></div><div id="algorithmGuide"></div></div><div class="card v2panel trace-panel"><p class="label">WORKED TRACE / SEE VALUES CHANGE</p><label class="guide-label">Example<select id="traceSelect"></select></label><div id="traceExample"></div></div>`;
document.querySelector('#learning').before(updates,visuals);document.querySelector('.hero-actions').insertAdjacentHTML('beforeend','<a class="secondary" href="#visuals">Architecture + DSA flows →</a><a class="secondary" href="#updates">Latest versions →</a>');
let guideStep=0;
function renderArchitecture(){const d=architectureDiagrams.find(d=>d.id===document.querySelector('#architectureSelect').value);document.querySelector('#architectureGuide').innerHTML=`<h3 class="guide-title">${esc(d.title)}</h3><p class="muted">${esc(d.note)}</p><div class="guide-layout"><div class="diagram-scroll">${diagramSVG(d)}</div><ol class="guide-explanation">${d.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></div><a class="secondary small" href="#learning/${d.track}">Practice related questions →</a>`}
function algorithmSVG(d){const marker=`algo-arrow-${d.id}`,height=d.steps.length*100+50;return `<svg viewBox="0 0 680 ${height}" role="img" aria-label="${esc(d.title)} learning flow"><title>${esc(d.title)} step flow</title><defs><marker id="${marker}" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8 Z" fill="var(--accent2)"/></marker></defs>${d.steps.map((s,i)=>{const y=40+i*100,parts=s.length>51?s.match(/.{1,48}(?:\s|$)/g)||[s]:[s];return `${i?`<path d="M340 ${y-60} L340 ${y-15}" stroke="var(--accent2)" stroke-width="2" marker-end="url(#${marker})"/>`:''}<rect x="45" y="${y-15}" width="590" height="55" rx="12" fill="${i===guideStep?'color-mix(in srgb,var(--accent) 15%,var(--panel))':'var(--panel2)'}" stroke="${i===guideStep?'var(--accent)':'var(--line)'}" stroke-width="2"/><text x="65" y="${y+16}" fill="var(--accent2)" font-size="16">${i+1}</text><text x="360" y="${y+(parts.length>1?6:16)}" text-anchor="middle" fill="var(--text)" font-size="14">${parts.slice(0,2).map((p,j)=>`<tspan x="360" dy="${j?18:0}">${esc(p.trim())}</tspan>`).join('')}</text>`}).join('')}</svg>`}
function renderAlgorithm(){const d=dsaVisuals.find(d=>d.id===document.querySelector('#algorithmSelect').value);if(!d){document.querySelector('#algorithmGuide').innerHTML='<p class="muted">No matching guides. Clear the search.</p>';return}guideStep=Math.min(guideStep,d.steps.length-1);document.querySelector('#algorithmGuide').innerHTML=`<h3 class="guide-title">${esc(d.title)}</h3><p class="muted">Use when: ${esc(d.when)}</p><p class="complexity-badge">${esc(d.complexity)}</p><p class="muted">Follow the learning sequence. Loop and branch details are in the pseudocode below.</p><div class="guide-layout"><div class="diagram-scroll">${algorithmSVG(d)}</div><div><div class="active-step" role="status"><p class="label">STEP ${guideStep+1} / ${d.steps.length}</p><h4>${esc(d.steps[guideStep])}</h4></div><div class="rating-actions"><button class="secondary small" id="previousGuideStep" ${guideStep===0?'disabled':''}>← Previous</button><button class="primary small" id="nextGuideStep" ${guideStep===d.steps.length-1?'disabled':''}>Next step →</button><button class="ghost small" id="resetGuideStep">Restart flow</button></div><h4>Worked example</h4><p>${esc(d.example)}</p><h4>Pseudocode / invariant</h4><pre class="guide-code">${esc(d.pseudo)}</pre><a class="table-link" href="https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/" target="_blank" rel="noreferrer">Algorithms reference ↗</a></div></div><a class="secondary small" href="#learning/dsa">Take a 1-mark DSA quiz →</a>`;document.querySelector('#previousGuideStep').onclick=()=>{guideStep--;renderAlgorithm()};document.querySelector('#nextGuideStep').onclick=()=>{guideStep++;renderAlgorithm()};document.querySelector('#resetGuideStep').onclick=()=>{guideStep=0;renderAlgorithm()};}
document.querySelector('#architectureSelect').onchange=renderArchitecture;document.querySelector('#algorithmSelect').onchange=()=>{guideStep=0;renderAlgorithm()};document.querySelector('#algorithmSearch').oninput=e=>{const list=dsaVisuals.filter(d=>`${d.title} ${d.when}`.toLowerCase().includes(e.target.value.toLowerCase()));document.querySelector('#algorithmSelect').innerHTML=list.map(d=>`<option value="${d.id}">${esc(d.title)}</option>`).join('');guideStep=0;renderAlgorithm()};renderArchitecture();renderAlgorithm();
const traceCases=[];
function traceCase(id,title,build){traceCases.push({id,title,steps:build()})}
traceCase('binary','Binary search · find 11',()=>{const a=[1,3,5,7,9,11,13],steps=[{values:a,active:[],caption:'Sorted input. Target = 11. Start with inclusive bounds low=0, high=6.'}];let lo=0,hi=a.length-1;while(lo<=hi){const mid=lo+Math.floor((hi-lo)/2);steps.push({values:a,active:[mid],caption:`low=${lo}, high=${hi}, mid=${mid}, value=${a[mid]}. ${a[mid]===11?'Found 11.':a[mid]<11?'Too small: discard indices through mid.':'Too large: discard indices from mid.'}`});if(a[mid]===11)break;if(a[mid]<11)lo=mid+1;else hi=mid-1;}return steps});
traceCase('two-sum','Two Sum · target 9',()=>{const a=[2,7,11,15],seen=new Map(),steps=[{values:a,active:[],caption:'Target 9. The map starts empty. Check the complement before inserting.'}];for(let i=0;i<a.length;i++){const need=9-a[i];if(seen.has(need)){steps.push({values:a,active:[seen.get(need),i],caption:`Value ${a[i]} needs ${need}; the map has it at index ${seen.get(need)}. Answer: [${seen.get(need)},${i}].`});break}seen.set(a[i],i);steps.push({values:a,active:[i],caption:`Value ${a[i]} needs ${need}, not yet found. Store ${a[i]} → ${i}.`});}return steps});
traceCase('window','Distinct substring · abba',()=>{const a=[...'abba'],last=new Map(),steps=[{values:a,active:[],caption:'left=0, best=0. The active cells will show the current unique window.'}];let left=0,best=0;for(let right=0;right<a.length;right++){const old=left;if(last.has(a[right]))left=Math.max(left,last.get(a[right])+1);last.set(a[right],right);best=Math.max(best,right-left+1);steps.push({values:a,active:Array.from({length:right-left+1},(_,i)=>left+i),caption:`Read '${a[right]}' at ${right}. left ${old} → ${left}; window length ${right-left+1}; best ${best}. ${right===3?'The earlier a is outside the window, so left does not move backward.':''}`});}return steps});
traceCase('bubble','Bubble sort · 4,1,3,2',()=>{const a=[4,1,3,2],steps=[{values:[...a],active:[],caption:'Compare neighbors. Larger values move toward the right each pass.'}];for(let end=a.length-1;end>0;end--){let changed=false;for(let i=0;i<end;i++){const before=[a[i],a[i+1]],swap=a[i]>a[i+1];if(swap){[a[i],a[i+1]]=[a[i+1],a[i]];changed=true}steps.push({values:[...a],active:[i,i+1],caption:`Compare ${before[0]} and ${before[1]}: ${swap?'swap':'already ordered'}. Unsorted boundary ends at ${end}.`});}if(!changed)break}steps.push({values:[...a],active:[],caption:'Sorted result: [1,2,3,4]. Worst-case time O(n²), auxiliary space O(1).'});return steps});
traceCase('prefix','Prefix sums · range 1..3',()=>{const a=[2,4,1,3],prefix=[0],steps=[{values:[...prefix],active:[0],caption:'Input [2,4,1,3]. prefix[0]=0. Query includes indices 1 through 3.'}];for(let i=0;i<a.length;i++){prefix.push(prefix[i]+a[i]);steps.push({values:[...prefix],active:[i+1],caption:`prefix[${i+1}] = ${prefix[i]} + ${a[i]} = ${prefix[i+1]}.`})}steps.push({values:[...prefix],active:[1,4],caption:'sum(1..3) = prefix[4] - prefix[1] = 10 - 2 = 8. No range scan is required.'});return steps});
traceCase('coin','Coin change · amount 6, coins 1,3,4',()=>{const dp=Array(7).fill(Infinity);dp[0]=0;const values=()=>dp.map(x=>Number.isFinite(x)?x:'∞'),steps=[{values:values(),active:[0],caption:'dp[0]=0; all other amounts are unreachable initially. Array index is amount.'}];for(let amount=1;amount<=6;amount++){for(const coin of [1,3,4])if(coin<=amount)dp[amount]=Math.min(dp[amount],dp[amount-coin]+1);steps.push({values:values(),active:[amount],caption:`Try all usable coins for amount ${amount}. Minimum count is ${dp[amount]}.${amount===6?' Two coins (3+3) beat greedy 4+1+1.':''}`});}return steps});
traceCase('bfs','BFS · A→B,C; B,C→D',()=>{const graph={A:['B','C'],B:['D'],C:['D'],D:[]},queue=['A'],visited=new Set(['A']),order=[],steps=[{values:['A'],active:[0],caption:'Queue [A]; visited {A}. Mark nodes when enqueued to avoid duplicate work.'}];while(queue.length){const node=queue.shift();order.push(node);for(const next of graph[node])if(!visited.has(next)){visited.add(next);queue.push(next)}steps.push({values:[...order],active:[order.length-1],caption:`Visit ${node}. Queue: [${queue.join(', ')}]. Visit order: [${order.join(', ')}].`});}return steps});
traceCase('brackets','Stack · validate ([])',()=>{const stack=[],steps=[{values:[],active:[],caption:'An empty stack starts validation. Expected pairs: () and [].'}];for(const ch of ['(','[',']',')']){const opening=['(','['].includes(ch);if(opening)stack.push(ch);else stack.pop();steps.push({values:[...stack],active:stack.length?[stack.length-1]:[],caption:`Read '${ch}': ${opening?'push opener':'match and pop the top opener'}. Stack ${stack.length?'has remaining openers':'is empty'}.`})}steps.push({values:[],active:[],caption:'All closes matched their top opener and final stack is empty: valid.'});return steps});
traceCase('merge','Merge sorted halves · [1,4] + [2,3]',()=>{const a=[1,4],b=[2,3],out=[],steps=[{values:[1,4,2,3],active:[],caption:'Merge sort has already sorted halves [1,4] and [2,3]. Now merge them.'}];let i=0,j=0;while(i<a.length||j<b.length){const value=j===b.length||i<a.length&&a[i]<=b[j]?a[i++]:b[j++];out.push(value);steps.push({values:[...out],active:[out.length-1],caption:`Append ${value}. Remaining left [${a.slice(i)}], right [${b.slice(j)}].`})}return steps});
traceCase('dijkstra','Dijkstra · A→B 2; B→C 1; A→C 5',()=>[{values:[0,'∞','∞'],active:[0],caption:'Distances for [A,B,C]. Source A starts at 0. All weights are nonnegative.'},{values:[0,2,5],active:[0],caption:'Settle A. Relax A→B to 2 and A→C to 5.'},{values:[0,2,3],active:[1],caption:'Settle B with distance 2. B→C gives 2+1=3, improving C from 5.'},{values:[0,2,3],active:[2],caption:'Settle C with distance 3. The stale C=5 heap entry must be ignored.'}]);
let tracePosition=0;document.querySelector('#traceSelect').innerHTML=traceCases.map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('');
function renderTrace(){const example=traceCases.find(t=>t.id===document.querySelector('#traceSelect').value),step=example.steps[tracePosition];document.querySelector('#traceExample').innerHTML=`<p class="label">TRACE ${tracePosition+1} / ${example.steps.length}</p><div class="trace-values" aria-label="Current values">${step.values.length?step.values.map((v,i)=>`<div class="trace-cell ${step.active.includes(i)?'active':''}"><strong>${esc(String(v))}</strong><small>${i}</small></div>`).join(''):'<p class="muted">Empty state</p>'}</div><p class="trace-caption" role="status">${esc(step.caption)}</p><div class="rating-actions"><button class="secondary small" id="traceBack" ${tracePosition===0?'disabled':''}>← Back</button><button class="primary small" id="traceNext" ${tracePosition===example.steps.length-1?'disabled':''}>Next change →</button><button class="ghost small" id="traceReset">Reset example</button></div>`;document.querySelector('#traceBack').onclick=()=>{tracePosition--;renderTrace()};document.querySelector('#traceNext').onclick=()=>{tracePosition++;renderTrace()};document.querySelector('#traceReset').onclick=()=>{tracePosition=0;renderTrace()}}
document.querySelector('#traceSelect').onchange=()=>{tracePosition=0;renderTrace()};renderTrace();

